### ISSUE TITLE
Error: Could not re-generate GraphQL schema thrown when deleting class

### ISSUE THREAD

**Issue by antas-marcin** [weaviate/weaviate#1296]
```
ERRO[0138] could not (re)build graphql provider          action=graphql_rebuild error="Could not re-generate GraphQL schema, because: Could not build GraphQL schema, because: buildGetClass: wrong propertyType for thing.Post.ofCategory; SingleRef class name 'Category' does not exist at goroutine 1092 [running]:
runtime/debug.Stack(0xc000555250, 0x1e47de0, 0xc001a546d0)
	/usr/local/Cellar/go/1.15.5/libexec/src/runtime/debug/stack.go:24 +0x9f
github.com/semi-technologies/weaviate/adapters/handlers/graphql.buildGraphqlSchema.func1.1(0xc0005561a0)
	/Users/marcin/workspace/go/src/github.com/semi-technologies/weaviate/adapters/handlers/graphql/schema.go:107 +0x57
panic(0x1e47de0, 0xc001a546d0)
	/usr/local/Cellar/go/1.15.5/libexec/src/runtime/panic.go:969 +0x1b9
github.com/semi-technologies/weaviate/adapters/handlers/graphql/local/get.(*classBuilder).classObject.func1(0x0)
	/Users/marcin/workspace/go/src/github.com/semi-technologies/weaviate/adapters/handlers/graphql/local/get/class_builder.go:133 +0x58b
github.com/graphql-go/graphql.(*Object).Fields(0xc000b52210, 0x2ba9850)
	/Users/marcin/workspace/go/src/github.com/semi-technologies/weaviate/vendor/github.com/graphql-go/graphql/definition.go:430 +0x6e
github.com/graphql-go/graphql.typeMapReducer(0xc000555e20, 0xc000cb1a10, 0x237e300, 0xc000b52210, 0xc000cb1a10, 0x0, 0x0)
	/Users/marcin/workspace/go/src/github.com/semi-technologies/weaviate/vendor/github.com/graphql-go/graphql/schema.go:325 +0x4ad
github.com/graphql-go/graphql.typeMapReducer(0xc000555e20, 0xc000cb1a10, 0x237e180, 0xc00249c600, 0xc00249c600, 0x0, 0x0)
	/Users/marcin/workspace/go/src/github.com/semi-technologies/weaviate/vendor/github.com/graphql-go/graphql/schema.go:273 +0xf11
github.com/graphql-go/graphql.typeMapReducer(0xc000555e20, 0xc000cb1a10, 0x237e300, 0xc000b52370, 0xc000b52370, 0xc000f87a00, 0x1f28160)
	/Users/marcin/workspace/go/src/github.com/semi-technologies/weaviate/vendor/github.com/graphql-go/graphql/schema.go:336 +0x64b
github.com/graphql-go/graphql.typeMapReducer(0xc000555e20, 0xc000cb1a10, 0x237e300, 0xc000b52420, 0xc000b52420, 0xc000555b00, 0x108b27c)
	/Users/marcin/workspace/go/src/github.com/semi-technologies/weaviate/vendor/github.com/graphql-go/graphql/schema.go:336 +0x64b
github.com/graphql-go/graphql.typeMapReducer(0xc000555e20, 0xc000cb1a10, 0x237e300, 0xc000b52840, 0x2, 0xc00249ce60, 0x1)
	/Users/marcin/workspace/go/src/github.com/semi-technologies/weaviate/vendor/github.com/graphql-go/graphql/schema.go:336 +0x64b
github.com/graphql-go/graphql.NewSchema(0xc000b52840, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/marcin/workspace/go/src/github.com/semi-technologies/weaviate/vendor/github.com/graphql-go/graphql/schema.go:106 +0x8fb
github.com/semi-technologies/weaviate/adapters/handlers/graphql.buildGraphqlSchema.func1(0xc0005561a0, 0x206889f, 0xb, 0x0, 0x0, 0x1edacc0, 0xc000cb19e0, 0x0, 0x2079a38, 0x1a, ...)
	/Users/marcin/workspace/go/src/github.com/semi-technologies/weaviate/adapters/handlers/graphql/schema.go:111 +0xde
github.com/semi-technologies/weaviate/adapters/handlers/graphql.buildGraphqlSchema(0xc000f868d0, 0x2ba9850, 0x0, 0x0, 0x23937a0, 0xc0003ff180, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/marcin/workspace/go/src/github.com/semi-technologies/weaviate/adapters/handlers/graphql/schema.go:114 +0x210
github.com/semi-technologies/weaviate/adapters/handlers/graphql.Build(0xc000f868d0, 0x2ba9850, 0x0, 0x0, 0x236d440, 0xc000124c00, 0x23937a0, 0xc0003ff180, 0x0, 0x0, ...)
	/Users/marcin/workspace/go/src/github.com/semi-technologies/weaviate/adapters/handlers/graphql/schema.go:58 +0x345
github.com/semi-technologies/weaviate/adapters/handlers/rest.rebuildGraphQL(0xc0006a26e0, 0xc0006a2730, 0x23937a0, 0xc0003ff180, 0x2386c80, 0x2ba9850, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/marcin/workspace/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/configure_server.go:73 +0x19e
github.com/semi-technologies/weaviate/adapters/handlers/rest.makeUpdateSchemaCall.func1(0xc0006a26e0, 0xc0006a2730)
	/Users/marcin/workspace/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/configure_server.go:50 +0x105
github.com/semi-technologies/weaviate/usecases/schema.(*Manager).TriggerSchemaUpdateCallbacks(0xc000afe370)
	/Users/marcin/workspace/go/src/github.com/semi-technologies/weaviate/usecases/schema/manager.go:139 +0x68
github.com/semi-technologies/weaviate/usecases/schema.(*Manager).saveSchema(0xc000afe370, 0x237dc00, 0xc002526e70, 0x1, 0x0)
	/Users/marcin/workspace/go/src/github.com/semi-technologies/weaviate/usecases/schema/manager.go:124 +0x225
github.com/semi-technologies/weaviate/usecases/schema.(*Manager).deleteClass(0xc000afe370, 0x237dc00, 0xc002526e70, 0xc0009b68b9, 0x8, 0x2062627, 0x5, 0x0, 0x0)
	/Users/marcin/workspace/go/src/github.com/semi-technologies/weaviate/usecases/schema/delete.go:69 +0x28b
github.com/semi-technologies/weaviate/usecases/schema.(*Manager).DeleteThing(0xc000afe370, 0x237dc00, 0xc002526e70, 0x0, 0xc0009b68b9, 0x8, 0x1, 0x1)
	/Users/marcin/workspace/go/src/github.com/semi-technologies/weaviate/usecases/schema/delete.go:40 +0xed
github.com/semi-technologies/weaviate/adapters/handlers/rest.(*schemaHandlers).deleteThing(0xc0008ba478, 0xc0006b2900, 0xc0009b68b9, 0x8, 0x0, 0x0, 0x0)
	/Users/marcin/workspace/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/handlers_schema.go:114 +0x93
github.com/semi-technologies/weaviate/adapters/handlers/rest/operations/schema.SchemaThingsDeleteHandlerFunc.Handle(0xc0004e4300, 0xc0006b2900, 0xc0009b68b9, 0x8, 0x0, 0x0, 0x0)
	/Users/marcin/workspace/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/operations/schema/schema_things_delete.go:32 +0x4e
github.com/semi-technologies/weaviate/adapters/handlers/rest/operations/schema.(*SchemaThingsDelete).ServeHTTP(0xc000896760, 0x2379e00, 0xc000b2e1c0, 0xc0006b2900)
	/Users/marcin/workspace/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/operations/schema/schema_things_delete.go:80 +0x292
github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0x2379e00, 0xc000b2e1c0, 0xc0006b2800)
	/Users/marcin/workspace/go/src/github.com/semi-technologies/weaviate/vendor/github.com/go-openapi/runtime/middleware/operation.go:28 +0x75
net/http.HandlerFunc.ServeHTTP(0xc00053e970, 0x2379e00, 0xc000b2e1c0, 0xc0006b2800)
	/usr/local/Cellar/go/1.15.5/libexec/src/net/http/server.go:2042 +0x44
github.com/semi-technologies/weaviate/adapters/handlers/rest.makeSetupMiddlewares.func1.1(0x2379e00, 0xc000b2e1c0, 0xc0006b2800)
	/Users/marcin/workspace/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/middlewares.go:35 +0xb7
net/http.HandlerFunc.ServeHTTP(0xc000896980, 0x2379e00, 0xc000b2e1c0, 0xc0006b2800)
	/usr/local/Cellar/go/1.15.5/libexec/src/net/http/server.go:2042 +0x44
github.com/go-openapi/runtime/middleware.NewRouter.func1(0x2379e00, 0xc000b2e1c0, 0xc0006b2100)
	/Users/marcin/workspace/go/src/github.com/semi-technologies/weaviate/vendor/github.com/go-openapi/runtime/middleware/router.go:77 +0x359
net/http.HandlerFunc.ServeHTTP(0xc00074bbc0, 0x2379e00, 0xc000b2e1c0, 0xc0006b2100)
	/usr/local/Cellar/go/1.15.5/libexec/src/net/http/server.go:2042 +0x44
github.com/go-openapi/runtime/middleware.Redoc.func1(0x2379e00, 0xc000b2e1c0, 0xc0006b2100)
	/Users/marcin/workspace/go/src/github.com/semi-technologies/weaviate/vendor/github.com/go-openapi/runtime/middleware/redoc.go:72 +0x28e
net/http.HandlerFunc.ServeHTTP(0xc00055e100, 0x2379e00, 0xc000b2e1c0, 0xc0006b2100)
	/usr/local/Cellar/go/1.15.5/libexec/src/net/http/server.go:2042 +0x44
github.com/go-openapi/runtime/middleware.Spec.func1(0x2379e00, 0xc000b2e1c0, 0xc0006b2100)
	/Users/marcin/workspace/go/src/github.com/semi-technologies/weaviate/vendor/github.com/go-openapi/runtime/middleware/spec.go:46 +0x190
net/http.HandlerFunc.ServeHTTP(0xc00055e140, 0x2379e00, 0xc000b2e1c0, 0xc0006b2100)
	/usr/local/Cellar/go/1.15.5/libexec/src/net/http/server.go:2042 +0x44
github.com/rs/cors.(*Cors).Handler.func1(0x2379e00, 0xc000b2e1c0, 0xc0006b2100)
	/Users/marcin/workspace/go/src/github.com/semi-technologies/weaviate/vendor/github.com/rs/cors/cors.go:200 +0x1b1
net/http.HandlerFunc.ServeHTTP(0xc000836200, 0x2379e00, 0xc000b2e1c0, 0xc0006b2100)
	/usr/local/Cellar/go/1.15.5/libexec/src/net/http/server.go:2042 +0x44
github.com/semi-technologies/weaviate/adapters/handlers/rest/swagger_middleware.AddMiddleware.func1(0x2379e00, 0xc000b2e1c0, 0xc0006b2100)
	/Users/marcin/workspace/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/swagger_middleware/swagger_middleware.go:37 +0xcb
net/http.HandlerFunc.ServeHTTP(0xc000885650, 0x2379e00, 0xc000b2e1c0, 0xc0006b2100)
	/usr/local/Cellar/go/1.15.5/libexec/src/net/http/server.go:2042 +0x44
github.com/semi-technologies/weaviate/adapters/handlers/rest.makeAddLogging.func1.1(0x2379e00, 0xc000b2e1c0, 0xc0006b2100)
	/Users/marcin/workspace/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/middlewares.go:82 +0x2f4
net/http.HandlerFunc.ServeHTTP(0xc000885680, 0x2379e00, 0xc000b2e1c0, 0xc0006b2100)
	/usr/local/Cellar/go/1.15.5/libexec/src/net/http/server.go:2042 +0x44
github.com/semi-technologies/weaviate/adapters/handlers/rest.addPreflight.func1(0x2379e00, 0xc000b2e1c0, 0xc0006b2100)
	/Users/marcin/workspace/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/middlewares.go:96 +0x73
net/http.HandlerFunc.ServeHTTP(0xc000836260, 0x2379e00, 0xc000b2e1c0, 0xc0006b2100)
	/usr/local/Cellar/go/1.15.5/libexec/src/net/http/server.go:2042 +0x44
github.com/semi-technologies/weaviate/adapters/handlers/rest.addLiveAndReadyness.func1(0x2379e00, 0xc000b2e1c0, 0xc0006b2100)
	/Users/marcin/workspace/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/middlewares.go:112 +0xa7
net/http.HandlerFunc.ServeHTTP(0xc000836280, 0x2379e00, 0xc000b2e1c0, 0xc0006b2100)
	/usr/local/Cellar/go/1.15.5/libexec/src/net/http/server.go:2042 +0x44
github.com/semi-technologies/weaviate/adapters/handlers/rest.addHandleRoot.func1(0x2379e00, 0xc000b2e1c0, 0xc0006b2100)
	/Users/marcin/workspace/go/src/github.com/semi-technologies/weaviate/adapters/handlers/rest/middlewares.go:50 +0x8f
net/http.HandlerFunc.ServeHTTP(0xc0008362a0, 0x2379e00, 0xc000b2e1c0, 0xc0006b2100)
	/usr/local/Cellar/go/1.15.5/libexec/src/net/http/server.go:2042 +0x44
net/http.serverHandler.ServeHTTP(0xc000b2e000, 0x2379e00, 0xc000b2e1c0, 0xc0006b2100)
	/usr/local/Cellar/go/1.15.5/libexec/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc000a7e000, 0x237db40, 0xc000daa000)
	/usr/local/Cellar/go/1.15.5/libexec/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.15.5/libexec/src/net/http/server.go:2969 +0x36c
"
```

**Comment by etiennedi** [comment]
Fixed in a recent version (around v1.16.x or v1.17.x)
