### ISSUE TITLE
Backup restore on empty class produces error

### ISSUE THREAD

**Issue by trengrj** [weaviate/weaviate#2330]
I'm getting the following error when restoring an empty class.

```
{'error': [{'message': 'corrupted backup file: invalid shard "Test"."sSzqkQ528Y5a"'}]}
```

Below are my reproduction steps on 1.15.5. Adding objects to the class allows the restore to complete.

```python
>>> import weaviate
>>> client = weaviate.Client("http://localhost:8080")
>>> client.schema.create_class({"class": "Test"})
>>> client.backup.create(backup_id="1", backend="filesystem")
{'backend': 'filesystem', 'classes': ['Test'], 'id': '1', 'path': '/var/lib/weaviate-backups/1', 'status': 'STARTED'}
>>> client.backup.get_create_status(backup_id="1", backend="filesystem")
{'backend': 'filesystem', 'id': '1', 'path': '/var/lib/weaviate-backups/1', 'status': 'SUCCESS'}
>>> client.backup.restore(backup_id="1", backend="filesystem")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.10/site-packages/weaviate/backup/backup.py", line 247, in restore
    raise UnexpectedStatusCodeException("Backup restore", response)
weaviate.exceptions.UnexpectedStatusCodeException: Backup restore! Unexpected status code: 422, with response body: {'error': [{'message': 'corrupted backup file: invalid shard "Test"."sSzqkQ528Y5a"'}]}
>>> client.data_object.create(class_name="Test", data_object={})
'7f07e1a0-061b-46fc-be27-b298a5701bd1'
>>> client.backup.create(backup_id="2", backend="filesystem")
{'backend': 'filesystem', 'classes': ['Test'], 'id': '2', 'path': '/var/lib/weaviate-backups/2', 'status': 'STARTED'}
>>> client.backup.get_create_status(backup_id="2", backend="filesystem")
{'backend': 'filesystem', 'id': '2', 'path': '/var/lib/weaviate-backups/2', 'status': 'SUCCESS'}
>>> client.backup.restore(backup_id="2", backend="filesystem")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.10/site-packages/weaviate/backup/backup.py", line 247, in restore
    raise UnexpectedStatusCodeException("Backup restore", response)
weaviate.exceptions.UnexpectedStatusCodeException: Backup restore! Unexpected status code: 422, with response body: {'error': [{'message': 'cannot restore class "Test" because it already exists'}]}
>>> client.schema.delete_all()
>>> client.backup.restore(backup_id="2", backend="filesystem")
{'backend': 'filesystem', 'classes': ['Test'], 'id': '2', 'path': '/var/lib/weaviate-backups/2', 'status': 'STARTED'}
>>> client.backup.get_restore_status(backup_id="2", backend="filesystem")
{'backend': 'filesystem', 'id': '2', 'path': '/var/lib/weaviate-backups/2', 'status': 'SUCCESS'}
```

Docker compose:

```yaml
---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: docker.io/semitechnologies/weaviate:1.15.5
    ports:
    - 8080:8080
    restart: on-failure:0
    volumes:
    - ./data:/var/lib/weaviate
    - ./backups:/var/lib/weaviate-backups
    environment:
      ENABLE_MODULES: "backup-filesystem"
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      BACKUP_FILESYSTEM_PATH: "/var/lib/weaviate-backups"
...
```

**Comment by etiennedi** [comment]
Is this still an issue or has this been fixed?
