### ISSUE TITLE
Batch import failure

### ISSUE THREAD

**Issue by vbanos** [weaviate/weaviate#2732]
Greetings from the Internet Archive,

We are trying to use weaviate via docker-compose and we have bumped into the following issue:
We have an ElasticSearch index with text extracted from PDF and we try to import these in weaviate. Import runs for a few thousand records and then it crashes.

Import script:
```
from datetime import datetime
import weaviate
from weaviate.util import generate_uuid5
from elasticsearch7 import Elasticsearch
from elasticsearch7.helpers import scan

weaviate_client = weaviate.Client('http://yyy-101:8080')
batch_size = 100
weaviate_client.batch.configure(batch_size=batch_size)

es_client = Elasticsearch(['xxx-101:9200', 'xxx-102:9200', 'xxx-103:9200'], timeout=90, max_retries=3)

results = scan(es_client,
     query={'query': {'match_all': {}}},
     index='nrc.gov-202302',
     doc_type='_doc')

with weaviate_client.batch as batch:
    for i, item in enumerate(results):
        doc = {}
        for key in ('url', 'surt_url', 'host', 'domain', 'tld', 'snippet', 'first_captured', 'title',
                    'content_type', 'language', 'text_extraction_method', 'version', 'publication_date'):
            val = item['_source'].get(key)
            if val:
                doc[key] = val

        uuid_document = generate_uuid5(doc, 'Document')
        batch.add_data_object(
            data_object=doc,
            class_name='Document',
            uuid=uuid_document
            )
        if i % batch_size == 0:
            print('Progress', i, datetime.utcnow())
```

A few thousand records are inserted correctly and the it crashes. You can see the detailed log here: [weaviate1.log.gz](https://github.com/weaviate/weaviate/files/10912510/weaviate1.log.gz)

Furthermore, after we try to run the import script again we get the following output:
```
python insert-to-weaviate-from-es.py
Traceback (most recent call last):
  File "insert-to-weaviate-from-es.py", line 8, in <module>
    weaviate_client = weaviate.Client('http://wwwb-esssd-101:8080')
  File "/opt/wayback-search-venv/lib/python3.8/site-packages/weaviate/client.py", line 126, in __init__
    self._connection = Connection(
  File "/opt/wayback-search-venv/lib/python3.8/site-packages/weaviate/connect/connection.py", line 542, in __init__
    self._server_version = self.get_meta()["version"]
  File "/opt/wayback-search-venv/lib/python3.8/site-packages/weaviate/connect/connection.py", line 560, in get_meta
    raise UnexpectedStatusCodeException("Meta endpoint", response)
weaviate.exceptions.UnexpectedStatusCodeException: Meta endpoint! Unexpected status code: 500, with response body: {'error': [{'message': 'rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup contextionary: no such host"'}]}.
sys:1: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('207.241.233.120', 49106), raddr=('207.241.233.73', 8080)>
```
weaviate has crashed (!)

We need to do `docker-compose down` and up to run the import script again.

Furthermore, we tried to see weaviate logs using `docker-compose up -d && docker-compose logs -f weaviate`
and we can't see anything useful.
During the whole time of the experiments we see just the following:
```
docker-compose up -d && docker-compose logs -f weaviate
Creating network "weaviate_default" with the default driver
Creating weaviate_weaviate_1         ... done
Creating weaviate_contextionary_1    ... done
Creating weaviate_text-spellcheck_1  ... done
Creating weaviate_ner-transformers_1 ... done
Creating weaviate_sum-transformers_1 ... done
Attaching to weaviate_weaviate_1
weaviate_1          | {"action":"config_load","config_file_path":"./weaviate.conf.json","level":"info","msg":"no config file specified, using default or environment based","time":"2023-03-07T17:57:39Z"}
weaviate_1          | {"action":"startup","default_vectorizer_module":"text2vec-contextionary","level":"info","msg":"the default vectorizer modules is set to \"text2vec-contextionary\", as a result all new schema classes without an explicit vectorizer setting, will use this vectorizer","time":"2023-03-07T17:57:39Z"}
weaviate_1          | {"action":"startup","auto_schema_enabled":true,"level":"info","msg":"auto schema enabled setting is set to \"true\"","time":"2023-03-07T17:57:39Z"}
weaviate_1          | {"action":"hnsw_vector_cache_prefill","count":50000,"index_id":"document_s0QegznVbnLW","level":"info","limit":1000000000000,"msg":"prefilled vector cache","time":"2023-03-07T17:57:40Z","took":616231307}
weaviate_1          | {"action":"startup_check_contextionary","error":"rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 172.21.0.5:9999: connect: connection refused\"","level":"warning","msg":"could not connect to contextionary at startup, trying again in 1 sec","time":"2023-03-07T17:57:41Z"}
weaviate_1          | {"action":"startup_check_contextionary","contextionaryVersion":"en0.16.0-v1.0.2","level":"info","msg":"found a valid contextionary version","requiredMinimumContextionaryVersion":"1.0.0","time":"2023-03-07T17:57:42Z"}
weaviate_1          | {"action":"sum_remote_wait_for_startup","error":"send check ready request: Get \"http://sum-transformers:8080/.well-known/ready\": dial tcp 172.21.0.3:8080: connect: connection refused","level":"warning","msg":"sum remote service not ready","time":"2023-03-07T17:57:43Z"}
weaviate_1          | {"action":"sum_remote_wait_for_startup","error":"send check ready request: Get \"http://sum-transformers:8080/.well-known/ready\": dial tcp 172.21.0.3:8080: connect: connection refused","level":"warning","msg":"sum remote service not ready","time":"2023-03-07T17:57:44Z"}
weaviate_1          | {"action":"sum_remote_wait_for_startup","error":"send check ready request: Get \"http://sum-transformers:8080/.well-known/ready\": dial tcp 172.21.0.3:8080: connect: connection refused","level":"warning","msg":"sum remote service not ready","time":"2023-03-07T17:57:45Z"}
weaviate_1          | {"action":"sum_remote_wait_for_startup","error":"send check ready request: Get \"http://sum-transformers:8080/.well-known/ready\": dial tcp 172.21.0.3:8080: connect: connection refused","level":"warning","msg":"sum remote service not ready","time":"2023-03-07T17:57:46Z"}
weaviate_1          | {"action":"sum_remote_wait_for_startup","error":"send check ready request: Get \"http://sum-transformers:8080/.well-known/ready\": dial tcp 172.21.0.3:8080: connect: connection refused","level":"warning","msg":"sum remote service not ready","time":"2023-03-07T17:57:47Z"}
weaviate_1          | {"action":"sum_remote_wait_for_startup","error":"send check ready request: Get \"http://sum-transformers:8080/.well-known/ready\": dial tcp 172.21.0.3:8080: connect: connection refused","level":"warning","msg":"sum remote service not ready","time":"2023-03-07T17:57:48Z"}
weaviate_1          | {"action":"sum_remote_wait_for_startup","error":"send check ready request: Get \"http://sum-transformers:8080/.well-known/ready\": dial tcp 172.21.0.3:8080: connect: connection refused","level":"warning","msg":"sum remote service not ready","time":"2023-03-07T17:57:49Z"}
weaviate_1          | {"action":"sum_remote_wait_for_startup","error":"send check ready request: Get \"http://sum-transformers:8080/.well-known/ready\": dial tcp 172.21.0.3:8080: connect: connection refused","level":"warning","msg":"sum remote service not ready","time":"2023-03-07T17:57:50Z"}
weaviate_1          | {"action":"sum_remote_wait_for_startup","error":"send check ready request: Get \"http://sum-transformers:8080/.well-known/ready\": dial tcp 172.21.0.3:8080: connect: connection refused","level":"warning","msg":"sum remote service not ready","time":"2023-03-07T17:57:51Z"}
weaviate_1          | {"action":"ner_remote_wait_for_startup","error":"send check ready request: Get \"http://ner-transformers:8080/.well-known/ready\": dial tcp 172.21.0.6:8080: connect: connection refused","level":"warning","msg":"ner remote service not ready","time":"2023-03-07T17:57:53Z"}
weaviate_1          | {"action":"ner_remote_wait_for_startup","error":"send check ready request: Get \"http://ner-transformers:8080/.well-known/ready\": dial tcp 172.21.0.6:8080: connect: connection refused","level":"warning","msg":"ner remote service not ready","time":"2023-03-07T17:57:54Z"}
weaviate_1          | {"action":"ner_remote_wait_for_startup","error":"send check ready request: Get \"http://ner-transformers:8080/.well-known/ready\": dial tcp 172.21.0.6:8080: connect: connection refused","level":"warning","msg":"ner remote service not ready","time":"2023-03-07T17:57:55Z"}
weaviate_1          | {"action":"ner_remote_wait_for_startup","error":"send check ready request: Get \"http://ner-transformers:8080/.well-known/ready\": dial tcp 172.21.0.6:8080: connect: connection refused","level":"warning","msg":"ner remote service not ready","time":"2023-03-07T17:57:56Z"}
weaviate_1          | {"action":"ner_remote_wait_for_startup","error":"send check ready request: Get \"http://ner-transformers:8080/.well-known/ready\": dial tcp 172.21.0.6:8080: connect: connection refused","level":"warning","msg":"ner remote service not ready","time":"2023-03-07T17:57:57Z"}
weaviate_1          | {"action":"restapi_management","level":"info","msg":"Serving weaviate at http://[::]:8080","time":"2023-03-07T17:57:58Z"}
```
There is nothing new when the import fails.

Any feedback is welcome. Thank you.

**Comment by kcm** [comment]
I'm seeing that the contextionary module is not running/reachable. Is it included in your docker-compose setup? If it isn't needed, you can remove it from your config and docker-compose. If it should be running, can you share your Weaviate and docker-compose configs?

**Comment by vbanos** [comment]
curl -o docker-compose.yml "https://configuration.weaviate.io/v2/docker-compose/docker-compose.yml?contextionary_compound_splitting=false&contextionary_language=en&contextionary_model=0.16.0&generative_openai=false&media_type=text&modules=modules&ner_module=true&ner_module_model=dbmdz-bert-large-cased-finetuned-conll03-english&qna_module=false&ref2vec_centroid=false&runtime=docker-compose&spellcheck_module=true&spellcheck_module_model=pyspellchecker-en&sum_module=true&sum_module_model=facebook-bart-large-cnn-1.0.0&text_module=text2vec-contextionary&weaviate_version=v1.17.4"

I'm just experimenting, I don't know if we need it or not.

So, the problem may be that the contextionary module crashes during the batch import?

**Comment by kcm** [comment]
Do you see any messages during the docker-compose startup, perhaps something like

`⠋ contextionary The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                                                 0.0s`

**Comment by kcm** [comment]
It could be. What architecture are you running on? The image is currently built for linux/amd64, so running it on e.g. an arm64 Mac would mean emulation, and that could be crashing. Can you provide `docker-compose logs contextionary`? Or perhaps try [`text2vec-transformers`](https://weaviate.io/developers/weaviate/modules/retriever-vectorizer-modules/text2vec-transformers)? You may find it's more flexible for your needs, anyway.

**Comment by vbanos** [comment]
We run the image on `model name      : Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz`

**Comment by kcm** [comment]
@vbanos a fix has been committed and released, as far as `contextionary` goes: https://hub.docker.com/r/semitechnologies/contextionary/tags?page=1&name=1.2.1
