### ISSUE TITLE
Panic in function knnSearchByVector.

### ISSUE THREAD

**Issue by 360AIVul** [weaviate/weaviate#3263]
1. Modify the parameter `k` in `TestHnswIndex` of [index_test.go](https://github.com/weaviate/weaviate/blob/14548a7c4a4aab48ac1348f991a7a11dd250e205/adapters/repos/db/vector/hnsw/index_test.go#L35) to `-1`.
```go
res, _, err := index.knnSearchByVector(testVectors[position], -1,     36, nil)
```
2. go test -v -run TestHnswIndex
```
=== RUN   TestHnswIndex
=== RUN   TestHnswIndex/searching_within_cluster_1
--- FAIL: TestHnswIndex (0.00s)
    --- FAIL: TestHnswIndex/searching_within_cluster_1 (0.00s)
panic: runtime error: index out of range [0] with length 0 [recovered]
        panic: runtime error: index out of range [0] with length 0

goroutine 105 [running]:
testing.tRunner.func1.2({0xe4e4c0, 0xc00272c1e0})
        /root/dev/go/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
        /root/dev/go/src/testing/testing.go:1529 +0x39f
panic({0xe4e4c0, 0xc00272c1e0})
        /root/dev/go/src/runtime/panic.go:884 +0x213
github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/priorityqueue.(*Queue).Pop(0x0?)
        /root/target/weaviate/adapters/repos/db/vector/hnsw/priorityqueue/queue.go:97 +0x90
github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).knnSearchByVector(0xc002760000, {0x16be6c0, 0x2, 0x2}, 0xffffffffffffffff, 0x0?, {0x0, 0x0})
        /root/target/weaviate/adapters/repos/db/vector/hnsw/search.go:574 +0x50f
github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.TestHnswIndex.func1(0x0?)
        /root/target/weaviate/adapters/repos/db/vector/hnsw/index_test.go:35 +0x58
testing.tRunner(0xc0000ebd40, 0xc002744b40)
        /root/dev/go/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
        /root/dev/go/src/testing/testing.go:1629 +0x3ea
```
It is caused by the negative value of `k`. Since the length of `res` will always be a non-positive value, once `res.Len()` reduces to zero but is still bigger than `k`, the program will be panic.
```python
#adapters/repos/db/vector/hnsw/search.go
for res.Len() > k {
	res.Pop()
}
```

**Comment by amityahav** [comment]
Hey i would like to take this!
