### ISSUE TITLE
Cannot filter by `location` property of `geoCoordinates` type

### ISSUE THREAD

**Issue by delamainer** [weaviate/weaviate#3332]
I have a class called `Items` with two properties: `name` and `location`. I want to be able to filter items using `location` property of type `geoCoordinates`.

Weaviate Version: `v1.20.4`
Go Version: `v1.20.5`
Go Weaviate Client Version: `v4.9.0`

To create `Items` class I use the following code:
```golang
func createItemsClass() error {
	return client.Schema().ClassCreator().WithClass(&models.Class{
		Class:      "Items",
		Vectorizer: "none",
		Properties: []*models.Property{
			{
				Name:     "name",
				DataType: []string{"text"},
			},
			{
				Name:     "location",
				DataType: []string{"geoCoordinates"},
			},
		},
	}).Do(context.Background())
}
```
To create an object I use the following code:
```golang
func createItem() *models.Object {
	return &models.Object{
		Class: "Items",
		Properties: map[string]any{
			"name": gofakeit.Name(),
			"location": models.GeoCoordinates{
				Latitude:  pointer(float32(gofakeit.Latitude())),
				Longitude: pointer(float32(gofakeit.Longitude())),
			},
		},
		Vector: createVector(),
	}
}
```
To read objects I use the following code:
```golang
func readItems() (*models.GraphQLResponse, error) {
	return client.GraphQL().
		Get().
		WithClassName("Items").
		WithNearVector((&graphql.NearVectorArgumentBuilder{}).WithVector(createVector())).
		WithFields(
			graphql.Field{Name: "name"},
			graphql.Field{
				Name: "location",
				Fields: []graphql.Field{
					{Name: "latitude"},
					{Name: "longitude"},
				},
			},
		).
		WithWhere(
			filters.Where().
				WithOperator(filters.WithinGeoRange).
				WithPath([]string{"location"}).
				WithValueGeoRange(&filters.GeoCoordinatesParameter{
					Latitude:    51.51,
					Longitude:   -0.09,
					MaxDistance: 2000,
				}),
		).
		Do(context.Background())
}
```

When I try to read objects I get the following error:
```
 explorer: get class: vector search: object vector search at index items: remote shard 2rKPjDyV9EHJ: send http request: Post "http://*.*.*.*:7001/indices/Items/shards/2rKPjDyV9EHJ/objects/_search": EOF
```

**Comment by delamainer** [comment]
From the pod logs:
```
2023/08/07 12:32:34 http: panic serving *.*.*.*:60630: interface conversion: interface {} is map[string]interface {}, not filters.GeoRange
goroutine 2299300 [running]:
net/http.(*conn).serve.func1()
    /usr/local/go/src/net/http/server.go:1854 +0xbf
panic({0x1616bc0, 0xc0073beae0})
    /usr/local/go/src/runtime/panic.go:890 +0x263
github.com/weaviate/weaviate/adapters/repos/db/inverted.(*Searcher).extractGeoFilter(0xc0051b3250?, 0xc006912070, {0x15f0120?, 0xc007ea3fb0}, {0xc00330c1b0?, 0xc00395cbf5?}, 0xa)
    /go/src/github.com/weaviate/weaviate/adapters/repos/db/inverted/searcher.go:354 +0x1d0
github.com/weaviate/weaviate/adapters/repos/db/inverted.(*Searcher).extractPropValuePair(0xc00395cc00, 0xc007ea3f20, {0xc0005ac088, 0x5})
    /go/src/github.com/weaviate/weaviate/adapters/repos/db/inverted/searcher.go:256 +0x5be
github.com/weaviate/weaviate/adapters/repos/db/inverted.(*Searcher).docIDs(0x40faca?, {0xc00395cc00?, 0x80?}, 0x78?, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
    /go/src/github.com/weaviate/weaviate/adapters/repos/db/inverted/searcher.go:171 +0x38
github.com/weaviate/weaviate/adapters/repos/db/inverted.(*Searcher).Objects(0x199?, {0x1c245e0, 0xc004560190}, 0x2702778?, 0xc0067cc4a0?, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...)
    /go/src/github.com/weaviate/weaviate/adapters/repos/db/inverted/searcher.go:82 +0x95
github.com/weaviate/weaviate/adapters/repos/db.(*Shard).objectSearch(0xc0003aca50, {0x1c245e0, 0xc004560190}, 0x0?, 0xc0004fa638, 0xc00330c1c0?, {0x0, 0x0, 0x0}, 0x0, ...)
    /go/src/github.com/weaviate/weaviate/adapters/repos/db/shard_read.go:218 +0x978
github.com/weaviate/weaviate/adapters/repos/db.(*Index).IncomingSearch(0xc002bbc480?, {0x1c245e0, 0xc004560190}, {0xc002ca801b, 0xc}, {0x0, 0x0, 0x0}, 0x237?, 0x380?, ...)
    /go/src/github.com/weaviate/weaviate/adapters/repos/db/index.go:1270 +0x286
github.com/weaviate/weaviate/usecases/sharding.(*RemoteIndexIncoming).Search(0xc0067cc908?, {0x1c245e0, 0xc004560190}, {0xc002ca800e, 0x5}, {0xc002ca801b, 0xc}, {0x0, 0x0, 0x0}, ...)
    /go/src/github.com/weaviate/weaviate/usecases/sharding/remote_index_incoming.go:191 +0x154
github.com/weaviate/weaviate/adapters/handlers/rest/clusterapi.(*indices).postSearchObjects.func1({0x1c23030, 0xc004a18a80}, 0xc004c46800)
    /go/src/github.com/weaviate/weaviate/adapters/handlers/rest/clusterapi/indices.go:599 +0x32a
net/http.HandlerFunc.ServeHTTP(0xc00395c680?, {0x1c23030?, 0xc004a18a80?}, 0x0?)
    /usr/local/go/src/net/http/server.go:2122 +0x2f
github.com/weaviate/weaviate/adapters/handlers/rest/clusterapi.(*indices).Indices.func1({0x1c23030, 0xc004a18a80}, 0xc004c46800)
    /go/src/github.com/weaviate/weaviate/adapters/handlers/rest/clusterapi/indices.go:164 +0x10f
net/http.HandlerFunc.ServeHTTP(0xc004a18a80?, {0x1c23030?, 0xc004a18a80?}, 0x184abf8?)
    /usr/local/go/src/net/http/server.go:2122 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0?, {0x1c23030, 0xc004a18a80}, 0xc004c46800)
    /usr/local/go/src/net/http/server.go:2500 +0x149
net/http.serverHandler.ServeHTTP({0x1c1f6e8?}, {0x1c23030, 0xc004a18a80}, 0xc004c46800)
    /usr/local/go/src/net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc003b582d0, {0x1c24688, 0xc0004f52f0})
    /usr/local/go/src/net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:3089 +0x5ed

```

**Comment by delamainer** [comment]
It works fine for a single replica, but once we have two or more replicas it fails.
