### ISSUE TITLE
500 Weaviate Error: Could not delete object from vector repo, cannot reach enough replicas

### ISSUE THREAD

**Issue by jaspersorrio** [weaviate/weaviate#3502]
Hi Team, 

I have not been able to find any documentation on why this happens & how to resolve it.

Weaviate Version 1.21

````
await client.data
  .deleter()
  .withClassName(input.className)
  .withId(input.id)
  .do();

Error: usage error (500): {"error":[{"message":"could not delete object from vector repo: delete from index \"item\": replicate deletion: shard=\"oHVbXNgobAOf\" broadcast: cannot reach enough replicas"}]}
    at /home/jasper/esc-sept-2023/node_modules/weaviate-ts-client/dist/index.js:1:9070
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: usage error (500): {"error":[{"message":"could not delete object from vector repo: delete from index \"item\": replicate deletion: shard=\"oHVbXNgobAOf\" broadcast: cannot reach enough replicas"}]}
    at /home/jasper/esc-sept-2023/node_modules/weaviate-ts-client/dist/index.js:1:9070
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
````

````
console.log(JSON.stringify(await weaviateClient.cluster.nodesStatusGetter().do(), null, 2));
{
  "nodes": [
    {
      "batchStats": {
        "queueLength": 0,
        "ratePerSecond": 468
      },
      "gitHash": "8172acb",
      "name": "weaviate-0",
      "shards": [
        {
          "class": "Item",
          "name": "5YbmqbvNIzRB",
          "objectCount": 14710
        },
        {
          "class": "Item",
          "name": "iecVJ4Fj5Oo5",
          "objectCount": 21253
        },
        {
          "class": "Item",
          "name": "oHVbXNgobAOf",
          "objectCount": 17413
        }
      ],
      "stats": {
        "objectCount": 53376,
        "shardCount": 3
      },
      "status": "HEALTHY",
      "version": "1.21.0"
    },
    {
      "batchStats": {
        "queueLength": 0,
        "ratePerSecond": 588
      },
      "gitHash": "8172acb",
      "name": "weaviate-1",
      "shards": [
        {
          "class": "Item",
          "name": "5YbmqbvNIzRB",
          "objectCount": 14794
        },
        {
          "class": "Item",
          "name": "iecVJ4Fj5Oo5",
          "objectCount": 21358
        },
        {
          "class": "Item",
          "name": "oHVbXNgobAOf",
          "objectCount": 17520
        }
      ],
      "stats": {
        "objectCount": 53672,
        "shardCount": 3
      },
      "status": "HEALTHY",
      "version": "1.21.0"
    },
    {
      "batchStats": {
        "queueLength": 0,
        "ratePerSecond": 678
      },
      "gitHash": "8172acb",
      "name": "weaviate-2",
      "shards": [
        {
          "class": "Item",
          "name": "5YbmqbvNIzRB",
          "objectCount": 14794
        },
        {
          "class": "Item",
          "name": "iecVJ4Fj5Oo5",
          "objectCount": 21358
        },
        {
          "class": "Item",
          "name": "oHVbXNgobAOf",
          "objectCount": 17520
        }
      ],
      "stats": {
        "objectCount": 53672,
        "shardCount": 3
      },
      "status": "HEALTHY",
      "version": "1.21.0"
    }
  ]
}
````

**Comment by jaspersorrio** [comment]
Update: 
Adding .withConsistencyLevel("ALL") to all queries doesn't fix the problem

**Comment by jaspersorrio** [comment]
I've managed to find another use facing this issue `broadcast: cannot reach enough replicas`

cc: @zainhas

https://forum.weaviate.io/t/weaviate-batch-writes-erroring-when-i-try-to-write-500000-data-from-spark-connector/270

**Comment by jaspersorrio** [comment]
Found the root of the issue

Weaviate node ran out of Disk Space causing broadcast to fail and error `broadcast: cannot reach enough replicas` to occur
