### ISSUE TITLE
Interrupted batch delete results in index corruption

### ISSUE THREAD

**Issue by kcm** [weaviate/weaviate#3548]
One pod in a multi-pod deployment crashed after repeating panics:

```
goroutine 4092680020 [sync.Mutex.Lock]:
runtime.gopark(0x4c498d59847915?, 0x1980?, 0xa0?, 0x61?, 0x7fdff6e3fe18?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0x10844131af8 sp=0x10844131ad8 pc=0x43bff6
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:387
runtime.semacquire1(0xc28b9b6824, 0x0?, 0x3, 0x1, 0xe7?)
	/usr/local/go/src/runtime/sema.go:160 +0x20f fp=0x10844131b60 sp=0x10844131af8 pc=0x44d78f
sync.runtime_SemacquireMutex(0x1978?, 0x80?, 0xd0b0e6fea0?)
	/usr/local/go/src/runtime/sema.go:77 +0x26 fp=0x10844131b98 sp=0x10844131b60 pc=0x46afc6
sync.(*Mutex).lockSlow(0xc28b9b6820)
	/usr/local/go/src/sync/mutex.go:171 +0x165 fp=0x10844131be8 sp=0x10844131b98 pc=0x48c9e5
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:90
sync.(*RWMutex).Lock(0xdf725b3b78?)
	/usr/local/go/src/sync/rwmutex.go:147 +0x36 fp=0x10844131c18 sp=0x10844131be8 pc=0x48e036
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*Memtable).setTombstone(0xc28b9b6820, {0xdf725b3b50, 0x10, 0x10}, {0x0, 0x0, 0x153be00?})
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/memtable.go:176 +0x1be fp=0x10844131d80 sp=0x10844131c18 pc=0xc6e55e
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*Bucket).Delete(0x10848dbf989?, {0xdf725b3b50?, 0x196f?, 0x10?}, {0x0?, 0xed0276daa0?, 0xd788ce9d40?})
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/bucket.go:642 +0xfc fp=0x10844131df8 sp=0x10844131d80 pc=0xc58b9c
github.com/weaviate/weaviate/adapters/repos/db.(*Shard).batchDeleteObject(0xc07c4e6ff0, {0x1df3409?, 0x0?}, {0xe7eb51f830, 0x24})
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/shard_read.go:443 +0xf8 fp=0x10844131e80 sp=0x10844131df8 pc=0xf16178
github.com/weaviate/weaviate/adapters/repos/db.(*deleteObjectsBatcher).deleteObjectOfBatchInLSM(0xcd3f9057d0, {0x1c26008, 0xc7d3ada150}, 0x0?, 0x0)
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/shard_write_batch_delete.go:109 +0x17d fp=0x10844131f28 sp=0x10844131e80 pc=0xf1949d
github.com/weaviate/weaviate/adapters/repos/db.(*deleteObjectsBatcher).deleteSingleBatchInLSM.func1(0x325e, 0x0?, 0x0?)
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/shard_write_batch_delete.go:86 +0xa5 fp=0x10844131fb8 sp=0x10844131f28 pc=0xf19105
github.com/weaviate/weaviate/adapters/repos/db.(*deleteObjectsBatcher).deleteSingleBatchInLSM.func3()
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/shard_write_batch_delete.go:90 +0x32 fp=0x10844131fe0 sp=0x10844131fb8 pc=0xf19032
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0x10844131fe8 sp=0x10844131fe0 pc=0x46f401
created by github.com/weaviate/weaviate/adapters/repos/db.(*deleteObjectsBatcher).deleteSingleBatchInLSM
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/shard_write_batch_delete.go:83 +0x17e

goroutine 4092674333 [runnable]:
runtime.gopark(0x4c498d52b93523?, 0x7f76317e1ef8?, 0x18?, 0x58?, 0x40?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0x108168883e8 sp=0x108168883c8 pc=0x43bff6
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:387
runtime.semacquire1(0xc28b9b682c, 0x0?, 0x3, 0x0, 0x37?)
	/usr/local/go/src/runtime/sema.go:160 +0x20f fp=0x10816888450 sp=0x108168883e8 pc=0x44d78f
sync.runtime_SemacquireRWMutexR(0x51b295?, 0x80?, 0x8?)
	/usr/local/go/src/runtime/sema.go:82 +0x26 fp=0x10816888488 sp=0x10816888450 pc=0x46b026
sync.(*RWMutex).RLock(...)
	/usr/local/go/src/sync/rwmutex.go:71
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*Memtable).getBySecondary(0xc28b9b6820, 0x0, {0xd4e8b0b080, 0x8, 0xd198abab60?})
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/memtable.go:104 +0x1d8 fp=0x10816888540 sp=0x10816888488 pc=0xc6d7d8
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*Bucket).GetBySecondaryIntoMemory(0xc07c4e70e0, 0xddf233e180?, {0xd4e8b0b080, 0x8, 0x40}, {0x0, 0x0, 0x0})
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/bucket.go:272 +0x131 fp=0x10816888618 sp=0x10816888540 pc=0xc55e51
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*Bucket).GetBySecondary(...)
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/bucket.go:252
github.com/weaviate/weaviate/adapters/repos/db.(*Shard).uuidFromDocID(0xc07c4e6ff0, 0x1df1dd2)
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/shard_read.go:405 +0xfe fp=0x10816888680 sp=0x10816888618 pc=0xf15f9e
github.com/weaviate/weaviate/adapters/repos/db.(*deleteObjectsBatcher).deleteObjectOfBatchInLSM(0xcd3f9057d0, {0x1c26008, 0xc7d3ada150}, 0xaaf4873cc54f4fbc?, 0x0)
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/shard_write_batch_delete.go:103 +0xdb fp=0x10816888728 sp=0x10816888680 pc=0xf193fb
github.com/weaviate/weaviate/adapters/repos/db.(*deleteObjectsBatcher).deleteSingleBatchInLSM.func1(0x1c27, 0x682d5dbc470f1bbc?, 0xbb?)
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/shard_write_batch_delete.go:86 +0xa5 fp=0x108168887b8 sp=0x10816888728 pc=0xf19105
github.com/weaviate/weaviate/adapters/repos/db.(*deleteObjectsBatcher).deleteSingleBatchInLSM.func3()
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/shard_write_batch_delete.go:90 +0x32 fp=0x108168887e0 sp=0x108168887b8 pc=0xf19032
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0x108168887e8 sp=0x108168887e0 pc=0x46f401
created by github.com/weaviate/weaviate/adapters/repos/db.(*deleteObjectsBatcher).deleteSingleBatchInLSM
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/shard_write_batch_delete.go:83 +0x17e
```

Querying the index now gives:

```
{"action":"bm25_search","level":"warning","msg":"Skipping pair in BM25: MapPair.Value should be 8 bytes long, but is 0.","time":"2023-09-18T18:29:13Z"}
```

**Comment by etiennedi** [comment]
Thanks, @kcm! Somehow we missed this ticket originally, but that's super valuable information. We'll try to come up with something to reproduce this consistently.

**Comment by alpe** [comment]
I took a 👀 into the code base to replicate the problem. I still have very limited context but I could not find any transactional or atomic behaviour on the batch operation. The `commitLogger` in the `MemTable` writes the changes to an `bufio.Writer` which then eventually flushes the state to disk. When this process is interrupted by an instance killed for example, there is no chance to persist the in-flight data.
It can make sense to reduce the amount of transient data by active flushing the buffer or using a smaller one which comes at higher IO costs. At the end of the batch a flush + file.sync() can make sense as well.

It would be good to understand the root cause for the interrupted batch operation.

Additionally, It can make sense to repair a broken file to restore the bucket but this may be incomplete.
This problem may affect https://github.com/weaviate/weaviate/issues/2124 as well.

**Comment by etiennedi** [comment]
Cc @parkerduckworth and @jeroiraz who have context on overall durability/crash recovery topics going on at the moment. I believe they're doing something similar for a BM25 index corruption at the moment.

**Comment by parkerduckworth** [comment]
> When this process is interrupted by an instance killed for example, there is no chance to persist the in-flight data.
It can make sense to reduce the amount of transient data by active flushing the buffer or using a smaller one which comes at higher IO costs. At the end of the batch a flush + file.sync() can make sense as well.

Great insight @alpe thanks for commenting here. As @etiennedi mentioned, @jeroiraz is working on this very thing.

You can check out the bugfix branch [here](https://github.com/weaviate/weaviate/compare/master...chore/consistency) to keep an eye on the progress. Please feel free to continue the conversation with any more questions or comments you may have

**Comment by etiennedi** [comment]
For the latest updates, see #4125, which contains info about mitigation, fixes, and now also an automatic script to reproduce this bug starting with an empty instance. Keeping this issue open until a fix is released, but would like to keep all comms on #4125, so we have a single source of truth. Thank you.
