### ISSUE TITLE
panic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by msj121** [weaviate/weaviate#3967]
### How to reproduce this bug?

Weaviate crashes on restart

### What is the expected behavior?

Should load back up

### What is the actual behavior?

```
weaviate-weaviate-1  | {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 1000 to 3000, took 7.96µs\n","new_size":3000,"previous_size":1000,"time":"2024-01-01T20:23:42Z","took":7960}
weaviate-weaviate-1  | {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 34328 to 42910, took 445.657µs\n","new_size":42910,"previous_size":34328,"time":"2024-01-01T20:23:42Z","took":445657}
weaviate-weaviate-1  | {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 3000 to 5000, took 25.458µs\n","new_size":5000,"previous_size":3000,"time":"2024-01-01T20:23:42Z","took":25458}
weaviate-weaviate-1  | {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 5000 to 7000, took 53.636µs\n","new_size":7000,"previous_size":5000,"time":"2024-01-01T20:23:42Z","took":53636}
weaviate-weaviate-1  | {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 7000 to 9000, took 23.259µs\n","new_size":9000,"previous_size":7000,"time":"2024-01-01T20:23:42Z","took":23259}
weaviate-weaviate-1  | {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 9000 to 11250, took 104.746µs\n","new_size":11250,"previous_size":9000,"time":"2024-01-01T20:23:42Z","took":104746}
weaviate-weaviate-1  | {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 11250 to 14062, took 35.822µs\n","new_size":14062,"previous_size":11250,"time":"2024-01-01T20:23:42Z","took":35822}
weaviate-weaviate-1  | {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 14062 to 17577, took 55.139µs\n","new_size":17577,"previous_size":14062,"time":"2024-01-01T20:23:42Z","took":55139}
weaviate-weaviate-1  | {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 17577 to 21971, took 68.706µs\n","new_size":21971,"previous_size":17577,"time":"2024-01-01T20:23:42Z","took":68706}
weaviate-weaviate-1  | {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 21971 to 27463, took 140.853µs\n","new_size":27463,"previous_size":21971,"time":"2024-01-01T20:23:42Z","took":140853}
weaviate-weaviate-1  | {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 27463 to 34328, took 189.332µs\n","new_size":34328,"previous_size":27463,"time":"2024-01-01T20:23:42Z","took":189332}
weaviate-weaviate-1  | {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 34328 to 42910, took 238.779µs\n","new_size":42910,"previous_size":34328,"time":"2024-01-01T20:23:42Z","took":238779}
weaviate-weaviate-1  | {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 42910 to 53637, took 240.025µs\n","new_size":53637,"previous_size":42910,"time":"2024-01-01T20:23:42Z","took":240025}
weaviate-weaviate-1  | {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 42910 to 53637, took 325.132µs\n","new_size":53637,"previous_size":42910,"time":"2024-01-01T20:23:42Z","took":325132}
weaviate-weaviate-1  | {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 53637 to 67046, took 296.023µs\n","new_size":67046,"previous_size":53637,"time":"2024-01-01T20:23:42Z","took":296023}
weaviate-weaviate-1  | {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 67046 to 83807, took 2.116813ms\n","new_size":83807,"previous_size":67046,"time":"2024-01-01T20:23:42Z","took":2116813}
weaviate-weaviate-1  | {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 83807 to 104758, took 304.302µs\n","new_size":104758,"previous_size":83807,"time":"2024-01-01T20:23:42Z","took":304302}
weaviate-weaviate-1  | {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 104758 to 130947, took 342.616µs\n","new_size":130947,"previous_size":104758,"time":"2024-01-01T20:23:42Z","took":342616}
weaviate-weaviate-1  | {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 53637 to 67046, took 258.006µs\n","new_size":67046,"previous_size":53637,"time":"2024-01-01T20:23:42Z","took":258006}
weaviate-weaviate-1  | {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 130947 to 163683, took 416.13µs\n","new_size":163683,"previous_size":130947,"time":"2024-01-01T20:23:42Z","took":416130}
weaviate-weaviate-1  | {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 163683 to 204603, took 572.122µs\n","new_size":204603,"previous_size":163683,"time":"2024-01-01T20:23:42Z","took":572122}
weaviate-weaviate-1  | {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 67046 to 83807, took 193.676µs\n","new_size":83807,"previous_size":67046,"time":"2024-01-01T20:23:42Z","took":193676}
weaviate-weaviate-1  | {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 204603 to 255753, took 780.164µs\n","new_size":255753,"previous_size":204603,"time":"2024-01-01T20:23:42Z","took":780164}
weaviate-weaviate-1  | {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 255753 to 319691, took 1.073063ms\n","new_size":319691,"previous_size":255753,"time":"2024-01-01T20:23:42Z","took":1073063}
weaviate-weaviate-1  | {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 83807 to 104758, took 322.136µs\n","new_size":104758,"previous_size":83807,"time":"2024-01-01T20:23:42Z","took":322136}
weaviate-weaviate-1  | {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 319691 to 399613, took 1.447106ms\n","new_size":399613,"previous_size":319691,"time":"2024-01-01T20:23:42Z","took":1447106}
weaviate-weaviate-1  | {"action":"hnsw_grow_index","level":"debug","msg":"index grown from 399613 to 499516, took 2.812539ms\n","new_size":499516,"previous_size":399613,"time":"2024-01-01T20:23:42Z","took":2812539}
weaviate-weaviate-1  | panic: runtime error: makeslice: len out of range
weaviate-weaviate-1  | 
weaviate-weaviate-1  | goroutine 197 [running]:
weaviate-weaviate-1  | github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.growIndexToAccomodateNode({0xc00efb8000, 0x19936, 0xc002ca77a0?}, 0x135f60200000000, {0x1dddf10, 0xc00366c380})
weaviate-weaviate-1  | 	/go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/maintenance.go:111 +0x114
weaviate-weaviate-1  | github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*Deserializer).ReadNode(0xc0028d3168, {0x1db2280, 0xc002ca77a0}, 0xc0025c8480)
weaviate-weaviate-1  | 	/go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/deserializer.go:172 +0x97
weaviate-weaviate-1  | github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*Deserializer).Do(0xc0023a1470?, 0x4e?, 0x0?, 0x4?)
weaviate-weaviate-1  | 	/go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/deserializer.go:108 +0x165
weaviate-weaviate-1  | github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).restoreFromDisk(0xc0027e2000)
weaviate-weaviate-1  | 	/go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/startup.go:90 +0x537
weaviate-weaviate-1  | github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).init(0xc0027e2000, {{0xc0022ed740, 0x2d}, {0x19ab090, 0x4}, 0xc003816420, 0xc0023a0570, 0xc0023a05b0, {0x1dddf10, 0xc00366c380}, ...})
weaviate-weaviate-1  | 	/go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/startup.go:32 +0x65
weaviate-weaviate-1  | github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.New({{0xc0022ed740, 0x2d}, {0x19ab090, 0x4}, 0xc003816420, 0xc0023a0570, 0xc0023a05b0, {0x1dddf10, 0xc00366c380}, {0x1dca418, ...}, ...}, ...)
weaviate-weaviate-1  | 	/go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/index.go:279 +0xce5
weaviate-weaviate-1  | github.com/weaviate/weaviate/adapters/repos/db.(*Shard).initVector(0xc0039da0f0, {0x1dc7ca0?, 0x2a27c60?})
weaviate-weaviate-1  | 	/go/src/github.com/weaviate/weaviate/adapters/repos/db/shard.go:297 +0x829
weaviate-weaviate-1  | github.com/weaviate/weaviate/adapters/repos/db.NewShard({0x1dc7ca0, 0x2a27c60}, 0x0, {0xc00390abb0, 0xc}, 0xc002ab1200, 0xc002a07b00?, 0xc0036ae240, 0xc0034deed0)
weaviate-weaviate-1  | 	/go/src/github.com/weaviate/weaviate/adapters/repos/db/shard.go:227 +0x3cb
weaviate-weaviate-1  | github.com/weaviate/weaviate/adapters/repos/db.(*LazyLoadShard).Load(0xc003724ac0, {0x1dc7ca0, 0x2a27c60})
weaviate-weaviate-1  | 	/go/src/github.com/weaviate/weaviate/adapters/repos/db/shard_lazyloader.go:100 +0x147
weaviate-weaviate-1  | github.com/weaviate/weaviate/adapters/repos/db.(*Index).initAndStoreShards.func2.1({0x16f04c0?, 0xc00376d388?}, {0x1de48e8?, 0xc003724ac0})
weaviate-weaviate-1  | 	/go/src/github.com/weaviate/weaviate/adapters/repos/db/index.go:334 +0xe5
weaviate-weaviate-1  | github.com/weaviate/weaviate/adapters/repos/db.(*Index).ForEachShard.(*shardMap).Range.func1({0x1654b80?, 0xc003707b40?}, {0x199fa40?, 0xc003724ac0})
weaviate-weaviate-1  | 	/go/src/github.com/weaviate/weaviate/adapters/repos/db/index.go:79 +0x90
weaviate-weaviate-1  | sync.(*Map).Range(0xc002ab1210, 0xc0028d3f58)
weaviate-weaviate-1  | 	/usr/local/go/src/sync/map.go:476 +0x228
weaviate-weaviate-1  | github.com/weaviate/weaviate/adapters/repos/db.(*shardMap).Range(...)
weaviate-weaviate-1  | 	/go/src/github.com/weaviate/weaviate/adapters/repos/db/index.go:78
weaviate-weaviate-1  | github.com/weaviate/weaviate/adapters/repos/db.(*Index).ForEachShard(0x3b9aca00?, 0x0?)
weaviate-weaviate-1  | 	/go/src/github.com/weaviate/weaviate/adapters/repos/db/index.go:382 +0x4e
weaviate-weaviate-1  | github.com/weaviate/weaviate/adapters/repos/db.(*Index).initAndStoreShards.func2()
weaviate-weaviate-1  | 	/go/src/github.com/weaviate/weaviate/adapters/repos/db/index.go:320 +0x8e
weaviate-weaviate-1  | created by github.com/weaviate/weaviate/adapters/repos/db.(*Index).initAndStoreShards in goroutine 1
weaviate-weaviate-1  | 	/go/src/github.com/weaviate/weaviate/adapters/repos/db/index.go:316 +0x30d
```

Keeps restarting currently....

### Supporting information

I have tons of Server capability available. Tons of RAM/HD/CPU. Also this is run on docker. 

More information about setup: https://github.com/weaviate/weaviate/issues/3823
All data was processed from scratch again (and not reloaded from the above issue)

I have used grpc python-client v4 to help speed up upload (with async indexing). A similar error existed with race conditions of trying to grow the vector index a few years ago.

### Server Version

1.23.0

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by msj121** [comment]
I restarted from scratch and removed (ie:commented it) the following from the collection/class:

  ```
# "invertedIndexConfig": {
  #   "indexNullState": True,
  #   "indexPropertyLength": False
  # },
  # "vectorIndexConfig": {
  #   "pq": {
  #       "enabled": True,
  #       "trainingLimit": 100000,
  #       "segments": 128 #384 dimensions
  #   },
  #   "skip": False,
  #   "ef": 64,
  #   "efConstruction": 128,
  #   "maxConnections": 32,
  # },
```

I also made sure that instead of looping through sets of objects and doing them individually with batching - I have grouped the objects in even larger supersets of 10 (ie: >1000 objects). I am having much fewer issues.

I think that there is some sort of race clause happening with concurrent uploads happening in "parallel" or swiftly together that causes issues. That's my best guess for this and other issues.
