### ISSUE TITLE
Weaviate connection deletion throws error

### ISSUE THREAD

**Issue by SalomonKisters** [weaviate/weaviate#4265]
### How to reproduce this bug?

Make a connection to weaviate using llamaindex, insert a document (which works) and wait until garbage collection fails at the end of the program

### What is the expected behavior?

Should just close

### What is the actual behavior?

Exception ignored in: <function Client.__del__ at 0x7fd985f79ab0>
Traceback (most recent call last):
  File "/home/salomon/.local/lib/python3.10/site-packages/weaviate/client.py", line 514, in __del__
  File "/home/salomon/.local/lib/python3.10/site-packages/weaviate/connect/v3.py", line 338, in close
  File "/home/salomon/.local/lib/python3.10/site-packages/requests/sessions.py", line 799, in close
  File "/home/salomon/.local/lib/python3.10/site-packages/requests/adapters.py", line 366, in close
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 222, in clear
  File "/usr/lib/python3/dist-packages/urllib3/_collections.py", line 95, in clear
TypeError: 'NoneType' object is not callable
sys:1: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 57910), raddr=('127.0.0.1', 8080)>

### Server Version

v1-23-0-release

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by SalomonKisters** [comment]
to anyone experiencing the issue: it was in my imports. Gradually remove your imports and add them back. These are my imports after, making it work: 
file 1:
import weaviate
import time
from llama_index.vector_stores.weaviate import WeaviateVectorStore
from llama_index.core import VectorStoreIndex,StorageContext,Settings
from IPython.display import Markdown, display
from llama_index.llms.openai_like import OpenAILike
from llama_index.core.vector_stores import ExactMatchFilter, MetadataFilters
from llama_index.embeddings.langchain import LangchainEmbedding
from langchain_community.embeddings import InfinityEmbeddings
file 2:
import weaviate
import time
from llama_index.vector_stores.weaviate import WeaviateVectorStore
from llama_index.core import VectorStoreIndex,StorageContext,SimpleDirectoryReader,Settings
from llama_index.embeddings.langchain import LangchainEmbedding
from langchain_community.embeddings import InfinityEmbeddings
