### ISSUE TITLE
Pread may read data incorrectly

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#4327]
### How to reproduce this bug?

I can only reproduce this with private data from an incident. After the incident is over, I will try to create dummy data that also triggers this.

### What is the expected behavior?

Data is read correctly

### What is the actual behavior?

Data is read as if the file was corrupted, resulting in panics:

For example, running `localhost:8080/v1/objects` results in:

```
panic: runtime error: slice bounds out of range [:12374997254589438622] with capacity 6338

goroutine 834 [running]:
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.ParseReplaceNodeIntoPread({0x17f5a20, 0x400388e000}, 0x1, 0x4002db6c60)
        /go/src/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/segment_serialization.go:184 +0x454
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*segmentCursorReplace).parseReplaceNodeInto(0x4003242900, {0x84a1dc?, 0x18c2?}, {0xffff3dde1010?, 0x17f0301?, 0x23afd40?})
        /go/src/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/cursor_segment_replace.go:152 +0x58
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*segmentCursorReplace).next(0x4003242900)
        /go/src/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/cursor_segment_replace.go:70 +0x60
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*CursorReplace).advanceInner(0x40033c6120, 0x0)
        /go/src/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/cursor_bucket_replace.go:210 +0x4c
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*CursorReplace).mergeDuplicatesInCurrentStateAndAdvance(0x40033c6120, {0x4002907850, 0x1, 0x23afd40?})

```

### Supporting information

PR #4321 likely fixes this (currently verifying). 

### Server Version

`v1.23.10`, likely many previous versions affected as well

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by etiennedi** [comment]
Fixed by #4321, to be released as `v1.22.x`, `v1.23.x`, and `v1.24.x` patches shortly.
