### ISSUE TITLE
Implement panic handling for all viable code paths

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate#4329]
## Motivation

As part of an (internal) incident, we have discovered that not all code paths have proper panic catching. This was discovered as a secondary symptom of the bug described in #4327.

In an ideal scenario, the bug described there should have returned a user error and not take down the whole system. However, the stack trace starts here:

```
        /go/src/github.com/weaviate/weaviate/adapters/repos/db/shard_read.go:299 +0x68
github.com/weaviate/weaviate/adapters/repos/db.(*Shard).ObjectSearch(0x4002464960, {0x1806368, 0x4003070300}, 0x40037fe180?, 0x0, 0x40037b0bb0?, {0x0?, 0x4003706d78?, 0x9c9948?}, 0x4003706d88?, ...)
        /go/src/github.com/weaviate/weaviate/adapters/repos/db/shard_read.go:205 +0x86c
github.com/weaviate/weaviate/adapters/repos/db.(*LazyLoadShard).ObjectSearch(0x40028661a0, {0x1806368, 0x4003070300}, 0x0?, 0xa4?, 0x0?, {0x0, 0x0, 0x0}, 0x0?, ...)
        /go/src/github.com/weaviate/weaviate/adapters/repos/db/shard_lazyloader.go:204 +0xb8
github.com/weaviate/weaviate/adapters/repos/db.(*Index).objectSearchByShard.func1()
        /go/src/github.com/weaviate/weaviate/adapters/repos/db/index.go:1217 +0x114
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x58
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 783
        /go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0x98
```

A new goroutine seems to be spawned as part of the `errgroup.Group`. This renders previous panic recovery useless because each recovery only tackles one goroutine. Any time we spawn new routines as part of a request call stack, we need to add explicit panic recovery again.

## Why handle panics at a high level?

This is meant as a secondary safety net. Ideally, we would always fix the root cause of any panic instead. However, this protects against not-yet-discovered bugs and other unexpected behavior. We do not rely on this for error handling, the only point of this is to turn something catastrophic into a user error as opposed to a server crash.

## Acceptance Criteria

- Identify where we spawn new goroutines as part of the request call stack and add explicit panic handling for each
- Return something generic to the user, such as "an internal error occurred"
- Log as much as we can
    - which collection does the request belong to
    - if it's a text query, log keywords
    - anything else that might be helpful in root cause analysis
- Note that a `recover()` statement swallows the track trace, so it should be printed again using `debug.PrintStack()` if a panic is caught

## Notes

Note that for every request there are basically two possible entrypoints:

1. Through the regular API -> usecases -> db, etc.
2. A proxied request from a different node in the cluster where the entrypoint is the cluster API

TODO: @etiennedi -> add sample stack traces for both

Both paths need to be handled.

**Comment by hoppe-weaviate** [comment]
Hello, I have seen a panic occurring with the following message "panic: not enough data to fit kmeans" and then the pods (2 weaviate replicas) each restarted. The following log was also present in the 3 instances:
```
{"action":"compress","level":"info","msg":"switching to compressed vectors","time":"2024-03-01T16:18:47Z"}
panic: not enough data to fit kmeans

goroutine 5533695 [running]:
github.com/weaviate/weaviate/adapters/repos/db/vector/ssdhelpers.(*ProductQuantizer).Fit.func2(0xf0)
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/ssdhelpers/product_quantization.go:365 +0x125
github.com/weaviate/weaviate/adapters/repos/db/vector/ssdhelpers.Concurrently.func1(0xf)
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/ssdhelpers/utils.go:32 +0x7d
created by github.com/weaviate/weaviate/adapters/repos/db/vector/ssdhelpers.Concurrently in goroutine 5533670
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/ssdhelpers/utils.go:29 +0xe5
```

**Comment by hoppe-weaviate** [comment]
Hello, I have come across a panic. There appears to have been a sudden increase in writes and queries to weaviate before this started.
```

panic: runtime error: makeslice: len out of range

goroutine 521 [running]:
github.com/weaviate/weaviate/adapters/repos/db/vector/cache.(*shardedLockCache[...]).Grow(0x1e1dfe0, 0x100000000000000)
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/cache/sharded_lock_cache.go:221 +0x1d7
github.com/weaviate/weaviate/adapters/repos/db/vector/compressionhelpers.(*quantizedVectorsCompressor[...]).PrefillCache(0x34630b8a000)
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/compressionhelpers/compression.go:212 +0x83
github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).prefillCache.func1()
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/startup.go:207 +0x7f
created by github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).prefillCache in goroutine 180
	/go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/startup.go:201 +0x9f
```

**Comment by etiennedi** [comment]
Another one encountered in the wild.
```
panic: class StandaloneBotsonic: shard Weaviatef1d0de22_2645_48ac_b170_cdd1f407352b: findNewLocalEntrypoint called on an empty hnsw graph

goroutine 4886353 [running]:
github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).findNewLocalEntrypoint(0x40900fe000, {0x186f6e0, 0x413474b9a8}, 0x0, 0x531)
        /go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/delete.go:608 +0x35c
github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*neighborFinderConnector).pickEntrypoint(0x429971fca8)
        /go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/neighbor_connections.go:416 +0xe0
github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*neighborFinderConnector).doAtLevel(0x429971fca8, 0x0)
        /go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/neighbor_connections.go:206 +0x9dc
github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*neighborFinderConnector).Do(0x429971fca8)
        /go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/neighbor_connections.go:81 +0x4c
github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).reconnectNeighboursOf(0x40900fe000?, 0x186f6e0?, 0x413474b9a0?, {0x420e3b0000?, 0x531?, 0x600?}, {0x0?, 0x0?}, 0x0?, 0x0?, ...)
        /go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/neighbor_connections.go:43 +0x9c
github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).reassignNeighbor(0x40900fe000, 0x531, {0x186f6e0, 0x416f297aa8}, 0x421371b438?)
        /go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/delete.go:446 +0x770
github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).reassignNeighborsOf.func1()
        /go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/delete.go:332 +0x134
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x58
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 4886445
        /go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0x98
```

**Comment by rthiiyer82** [comment]
https://github.com/weaviate/weaviate/issues/4329#issuecomment-1973623218

This panic is fixedc in 1.24.1
