### ISSUE TITLE
segmentation violation panic with deletion concurrency > 1

### ISSUE THREAD

**Issue by rthiiyer82** [weaviate/weaviate#4427]
### How to reproduce this bug?

1. Start Server with `TOMBSTONE_DELETION_CONCURRENCY=1000` and `ASYNC_INDEXING: True`
2. Run the below script

```
import datetime
import requests
import sys
import time
import weaviate
import uuid
import numpy as np

from loguru import logger
from typing import Optional


num_objects = 100000

def reset_schema(client: weaviate.Client, class_names):
    client.schema.delete_all()
    for class_name in class_names:
        class_obj = {
            "vectorizer": "none",
            "vectorIndexConfig": {
                "efConstruction": 128,
                "maxConnections": 16,
                "ef": 256,
                "cleanupIntervalSeconds": 10,
                "pq":{
                    "enabled": False,  # Enable PQ
                    "trainingLimit": 100000
                }
            },
            "class": class_name,
            "invertedIndexConfig": {
                "indexTimestamps": False,
            },
            "properties": [
                {"dataType": ["string"], "name": "name"},
                {"dataType": ["int"], "name": "index"},
            ],
            
        }
        client.schema.create_class(class_obj)


def handle_errors(results: Optional[dict]) -> None:
    """
    Handle error message from batch requests logs the message as an info message.
    Parameters
    ----------
    results : Optional[dict]
        The returned results for Batch creation.
    """
    if results is not None:
        for result in results:
            if (
                "result" in result
                and "errors" in result["result"]
                and "error" in result["result"]["errors"]
            ):
                for message in result["result"]["errors"]["error"]:
                    logger.error(message["message"])



def success(msg):
    logger.success(msg)


def fatal(msg):
    logger.error(msg)
    sys.exit(1)


def load_records(client: weaviate.Client, class_name="Class"):
    client.batch.configure(batch_size=100, callback=handle_errors)
    with client.batch as batch:
        for i in range(num_objects):
            if i % 100 == 0:
                logger.info(f"Class: {class_name} - writing record {i}/{num_objects}")
            data_object = {"name": f"object#{i}", "index": i}
            vector = np.random.rand(32, 1)
            batch.add_data_object(
                data_object=data_object,
                vector=vector,
                class_name=class_name,
                uuid=uuid.UUID(int=i),
            )
    logger.info(f"Finished writing {num_objects} records")

def hostname(client: weaviate.Client):
    host = client._connection.url
    return host


node1_client = weaviate.Client("http://localhost:8080")

class_names = ["Class_A", "Class_B"]
reset_schema(node1_client, class_names)

logger.info("Inserting data...")
for class_name in class_names:
    load_records(node1_client, class_name)

def update_schema(client: weaviate.Client, class_names):
    for class_name in class_names:
        class_obj = {
            "vectorizer": "none",
            "vectorIndexConfig": {
                "efConstruction": 128,
                "maxConnections": 16,
                "ef": 256,
                "cleanupIntervalSeconds": 10,
                "pq":{
                    "enabled": True,  # Enable PQ
                    "trainingLimit": 100000
                }
            },
            "class": class_name,
            "invertedIndexConfig": {
                "indexTimestamps": False,
            }
        }
        client.schema.update_config(class_name, class_obj)

class_names = ["Class_A", "Class_B"]
update_schema(node1_client, class_names)

def load_new_records(client: weaviate.Client, class_name="Class"):
    client.batch.configure(batch_size=100, callback=handle_errors)
    with client.batch as batch:
        for i in range(num_objects):
            if i % 100 == 0:
                logger.info(f"Class: {class_name} - writing record {i}/{num_objects}")
            data_object = {"name": f"object#{i} hello", "index": i+1}
            vector = np.random.rand(32, 1)
            batch.add_data_object(
                data_object=data_object,
                vector=vector,
                class_name=class_name,
                uuid=uuid.UUID(int=i),
            )
    logger.info(f"Finished writing {num_objects} records")

logger.info("Inserting data on updated class...")
for class_name in class_names:
    load_new_records(node1_client, class_name)
```

### What is the expected behavior?

No Panic or Crash

### What is the actual behavior?

```weaviate-weaviate-node-1-1  | panic: runtime error: invalid memory address or nil pointer dereference
2024-03-08 10:03:03 weaviate-weaviate-node-1-1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x9c7238]
2024-03-08 10:03:03 weaviate-weaviate-node-1-1  | 
2024-03-08 10:03:03 weaviate-weaviate-node-1-1  | goroutine 743310 [running]:
2024-03-08 10:03:03 weaviate-weaviate-node-1-1  | github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).searchLayerByVectorWithDistancer(0x40001c0f00, {0x403f73fa00, 0x20, 0x20}, 0x0?, 0x1, 0x1, {0x0?, 0x0?}, {0x0, ...})
2024-03-08 10:03:03 weaviate-weaviate-node-1-1  |       /go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/search.go:271 +0x7c8
2024-03-08 10:03:03 weaviate-weaviate-node-1-1  | github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).findBestEntrypointForNode(0x40001c0f00, 0x1864200?, 0x0, 0x3?, {0x403f73fa00, 0x20, 0x20}, {0x0?, 0x0?})
2024-03-08 10:03:03 weaviate-weaviate-node-1-1  |       /go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/index.go:431 +0x1d8
2024-03-08 10:03:03 weaviate-weaviate-node-1-1  | github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).reassignNeighbor(0x40001c0f00, 0x177eb, {0x186f6e0, 0x4030fd9380}, 0x404fd2a538?)
2024-03-08 10:03:03 weaviate-weaviate-node-1-1  |       /go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/delete.go:406 +0x41c
2024-03-08 10:03:03 weaviate-weaviate-node-1-1  | github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).reassignNeighborsOf.func1()
2024-03-08 10:03:03 weaviate-weaviate-node-1-1  |       /go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/delete.go:332 +0x134
2024-03-08 10:03:03 weaviate-weaviate-node-1-1  | golang.org/x/sync/errgroup.(*Group).Go.func1()
2024-03-08 10:03:03 weaviate-weaviate-node-1-1  |       /go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x58
2024-03-08 10:03:03 weaviate-weaviate-node-1-1  | created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 742641
2024-03-08 10:03:03 weaviate-weaviate-node-1-1  |       /go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0x98
2024-03-08 10:03:03 weaviate-weaviate-node-1-1  | panic: runtime error: invalid memory address or nil pointer dereference
2024-03-08 10:03:03 weaviate-weaviate-node-1-1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x9c7238]
2024-03-08 10:03:03 weaviate-weaviate-node-1-1  | 
2024-03-08 10:03:03 weaviate-weaviate-node-1-1  | goroutine 743586 [running]:
2024-03-08 10:03:03 weaviate-weaviate-node-1-1  | github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).searchLayerByVectorWithDistancer(0x40001c0f00, {0x403fd61b80, 0x20, 0x20}, 0x0?, 0x1, 0x2, {0x0?, 0x0?}, {0x0, ...})
2024-03-08 10:03:03 weaviate-weaviate-node-1-1  |       /go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/search.go:271 +0x7c8
2024-03-08 10:03:03 weaviate-weaviate-node-1-1  | github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).findBestEntrypointForNode(0x40001c0f00, 0x1864200?, 0x0, 0x403f3c7700?, {0x403fd61b80, 0x20, 0x20}, {0x0?, 0x0?})
2024-03-08 10:03:03 weaviate-weaviate-node-1-1  |       /go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/index.go:431 +0x1d8
2024-03-08 10:03:03 weaviate-weaviate-node-1-1  | github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).reassignNeighbor(0x40001c0f00, 0x1757b, {0x186f6e0, 0x4030fd9380}, 0x400277f560?)
2024-03-08 10:03:03 weaviate-weaviate-node-1-1  |       /go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/delete.go:406 +0x41c
2024-03-08 10:03:03 weaviate-weaviate-node-1-1  | github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw.(*hnsw).reassignNeighborsOf.func1()
2024-03-08 10:03:03 weaviate-weaviate-node-1-1  |       /go/src/github.com/weaviate/weaviate/adapters/repos/db/vector/hnsw/delete.go:332 +0x134
2024-03-08 10:03:03 weaviate-weaviate-node-1-1  | golang.org/x/sync/errgroup.(*Group).Go.func1()
2024-03-08 10:03:03 weaviate-weaviate-node-1-1  |       /go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x58
2024-03-08 10:03:03 weaviate-weaviate-node-1-1  | created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 742641
2024-03-08 10:03:03 weaviate-weaviate-node-1-1  |       /go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0x98
````

And server restarts

### Supporting information

Reproducible on Weaviate v1.24.1 

### Server Version

1.24.1

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by rthiiyer82** [comment]
Verified on v1.24.2. Segementation violation panic appears to be fixed.
