### ISSUE TITLE
After the server shuts down abnormally and restarts the container, an error message is reported

### ISSUE THREAD

**Issue by kingbug-nightraid** [weaviate/weaviate#5268]
### How to reproduce this bug?

{"action":"lsm_recover_from_active_wal","class":"Vector_index_73f8bf64_94ef_42b9_86b3_b933c9c30480_Node","index":"vector_index_73f8bf64_94ef_42b9_86b3_b933c9c30480_node","level":"warning","msg":"active write-ahead-log found. Did weaviate crash prior to this? Trying to recover...","path":"/var/lib/weaviate/vector_index_73f8bf64_94ef_42b9_86b3_b933c9c30480_node_fKGmqw3I7WTZ_lsm/objects/segment-1719904829431418659.wal","shard":"fKGmqw3I7WTZ","time":"2024-07-02T07:20:37Z"} {"action":"lsm_recover_from_active_wal_success","class":"Vector_index_73f8bf64_94ef_42b9_86b3_b933c9c30480_Node","index":"vector_index_73f8bf64_94ef_42b9_86b3_b933c9c30480_node","level":"info","msg":"successfully recovered from write-ahead-log","path":"/var/lib/weaviate/vector_index_73f8bf64_94ef_42b9_86b3_b933c9c30480_node_fKGmqw3I7WTZ_lsm/objects/segment-1719904829431418659.wal","shard":"fKGmqw3I7WTZ","time":"2024-07-02T07:20:37Z"} panic: runtime error: 

index out of range [0] with length 0 goroutine 1 [running]: github.com/weaviate/weaviate/adapters/repos/db/inverted.NewJsonPropertyLengthTracker({0xc02f47e070, 0x61}) /go/src/github.com/weaviate/weaviate/adapters/repos/db/inverted/new_prop_length_tracker.go:83 +0x734 github.com/weaviate/weaviate/adapters/repos/db.(*Shard).initNonVector(0xc013749260, {0x1b9b100?, 0xc002ce0de0?}, 0x80?) /go/src/github.com/weaviate/weaviate/adapters/repos/db/shard.go:190 +0x26a github.com/weaviate/weaviate/adapters/repos/db.NewShard({0x1b9b100, 0xc002ce0de0}, 0x0, {0xc003a64b10, 0xc}, 0xc00561ba00, 0x3?, 0xc002ce1080) /go/src/github.com/weaviate/weaviate/adapters/repos/db/shard.go:120 +0x612 github.com/weaviate/weaviate/adapters/repos/db.NewIndex({_, _}, {{0xc00004a016, 0x11}, {0xc00371eb40, 0x36}, 0x2710, {{0x50, 0x5a}, {0x50, ...}}, ...}, ...) /go/src/github.com/weaviate/weaviate/adapters/repos/db/index.go:140 +0x777 github.com/weaviate/weaviate/adapters/repos/db.(*DB).init(0xc002fb7340, {0x1b9b100, 0xc002ce0de0}) /go/src/github.com/weaviate/weaviate/adapters/repos/db/init.go:57 +0x565 github.com/weaviate/weaviate/adapters/repos/db.(*DB).WaitForStartup(0xc002fb7340, {0x1b9b100?, 0xc002ce0de0?}) /go/src/github.com/weaviate/weaviate/adapters/repos/db/repo.go:81 +0x28 github.com/weaviate/weaviate/adapters/handlers/rest.configureAPI(0xc0003bc800) /go/src/github.com/weaviate/weaviate/adapters/handlers/rest/configure_api.go:261 +0x2214 github.com/weaviate/weaviate/adapters/handlers/rest.(*Server).ConfigureAPI(...) /go/src/github.com/weaviate/weaviate/adapters/handlers/rest/server.go:68 main.main() /go/src/github.com/weaviate/weaviate/cmd/weaviate-server/main.go:62 +0x475

### What is the expected behavior?

how to resolve it

### What is the actual behavior?

index out of range [0] with length 0 goroutine 1 [running]: github.com/weaviate/weaviate/adapters/repos/db/inverted.NewJsonPropertyLengthTracker({0xc02f47e070, 0x61}) /go/src/github.com/weaviate/weaviate/adapters/repos/db/inverted/new_prop_length_tracker.go:83 +0x734 github.com/weaviate/weaviate/adapters/repos/db.(*Shard).initNonVector(0xc013749260, {0x1b9b100?, 0xc002ce0de0?}, 0x80?) /go/src/github.com/weaviate/weaviate/adapters/repos/db/shard.go:190 +0x26a github.com/weaviate/weaviate/adapters/repos/db.NewShard({0x1b9b100, 0xc002ce0de0}, 0x0, {0xc003a64b10, 0xc}, 0xc00561ba00, 0x3?, 0xc002ce1080) /go/src/github.com/weaviate/weaviate/adapters/repos/db/shard.go:120 +0x612 github.com/weaviate/weaviate/adapters/repos/db.NewIndex({_, _}, {{0xc00004a016, 0x11}, {0xc00371eb40, 0x36}, 0x2710, {{0x50, 0x5a}, {0x50, ...}}, ...}, ...) /go/src/github.com/weaviate/weaviate/adapters/repos/db/index.go:140 +0x777 github.com/weaviate/weaviate/adapters/repos/db.(*DB).init(0xc002fb7340, {0x1b9b100, 0xc002ce0de0}) /go/src/github.com/weaviate/weaviate/adapters/repos/db/init.go:57 +0x565 github.com/weaviate/weaviate/adapters/repos/db.(*DB).WaitForStartup(0xc002fb7340, {0x1b9b100?, 0xc002ce0de0?}) /go/src/github.com/weaviate/weaviate/adapters/repos/db/repo.go:81 +0x28 github.com/weaviate/weaviate/adapters/handlers/rest.configureAPI(0xc0003bc800) /go/src/github.com/weaviate/weaviate/adapters/handlers/rest/configure_api.go:261 +0x2214 github.com/weaviate/weaviate/adapters/handlers/rest.(*Server).ConfigureAPI(...) /go/src/github.com/weaviate/weaviate/adapters/handlers/rest/server.go:68 main.main() /go/src/github.com/weaviate/weaviate/cmd/weaviate-server/main.go:62 +0x475

### Server Version

1.19.0

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by rthiiyer82** [comment]
Hey @kingbug-nightraid  thank you for reporting the issue. I see you are using Weaviate version 1.19.0. We have improved our database and have addressed many issues in our latest versions. Please see if you can reproduce the above panic in latest version of Weaviate core database.
If yes, it would be nice if you could provide more context and information on schema structure, number of objects, node setup etc.
