### ISSUE TITLE
Nil pointer deref when loading sum-transformers module

### ISSUE THREAD

**Issue by Southclaws** [weaviate/weaviate#5398]
### How to reproduce this bug?

As far as I can tell, just adding `sum-transformers` to ENABLED_MODULES is causing this.

### What is the expected behavior?

If something is wrong, at least a useful error message.

### What is the actual behavior?

```
storyden-weaviate-1  | {"action":"startup","default_vectorizer_module":"text2vec-transformers","level":"info","msg":"the default vectorizer modules is set to \"text2vec-transformers\", as a result all new schema classes without an explicit vectorizer setting, will use this vectorizer","time":"2024-07-18T18:55:07Z"}
storyden-weaviate-1  | {"action":"startup","auto_schema_enabled":true,"level":"info","msg":"auto schema enabled setting is set to \"true\"","time":"2024-07-18T18:55:07Z"}
storyden-weaviate-1  | {"level":"info","msg":"No resource limits set, weaviate will use all available memory and CPU. To limit resources, set LIMIT_RESOURCES=true","time":"2024-07-18T18:55:07Z"}
storyden-weaviate-1  | {"level":"info","msg":"open cluster service","servers":{"node1":8300},"time":"2024-07-18T18:55:07Z"}
storyden-weaviate-1  | {"address":"172.19.0.6:8301","level":"info","msg":"starting cloud rpc server ...","time":"2024-07-18T18:55:07Z"}
storyden-weaviate-1  | {"level":"info","msg":"starting raft sub-system ...","time":"2024-07-18T18:55:07Z"}
storyden-weaviate-1  | {"address":"172.19.0.6:8300","level":"info","msg":"tcp transport","tcpMaxPool":3,"tcpTimeout":10000000000,"time":"2024-07-18T18:55:07Z"}
storyden-weaviate-1  | {"level":"info","msg":"loading local db","time":"2024-07-18T18:55:07Z"}
storyden-weaviate-1  | {"level":"info","msg":"database has been successfully loaded","n":0,"time":"2024-07-18T18:55:07Z"}
storyden-weaviate-1  | {"level":"info","metadata_only_voters":false,"msg":"construct a new raft node","name":"node1","time":"2024-07-18T18:55:07Z"}
storyden-weaviate-1  | {"action":"raft","index":21,"level":"info","msg":"raft initial configuration","servers":"[[{Suffrage:Voter ID:node1 Address:172.19.0.6:8300}]]","time":"2024-07-18T18:55:07Z"}
storyden-weaviate-1  | {"action":"raft","follower":{},"leader-address":"","leader-id":"","level":"info","msg":"raft entering follower state","time":"2024-07-18T18:55:07Z"}
storyden-weaviate-1  | {"last_snapshot_index":0,"last_store_applied_index":0,"last_store_log_applied_index":14,"level":"info","msg":"raft node constructed","raft_applied_index":0,"raft_last_index":23,"time":"2024-07-18T18:55:07Z"}
storyden-weaviate-1  | {"action":"bootstrap","error":"could not join a cluster from [172.19.0.6:8300]","level":"warning","msg":"failed to join cluster, will notify next if voter","servers":["172.19.0.6:8300"],"time":"2024-07-18T18:55:09Z","voter":true}
storyden-weaviate-1  | {"action":"bootstrap","candidates":[{"Suffrage":0,"ID":"node1","Address":"172.19.0.6:8300"}],"level":"info","msg":"starting cluster bootstrapping","time":"2024-07-18T18:55:09Z"}
storyden-weaviate-1  | {"action":"bootstrap","error":"bootstrap only works on new clusters","level":"error","msg":"could not bootstrapping cluster","time":"2024-07-18T18:55:09Z"}
storyden-weaviate-1  | {"action":"bootstrap","level":"info","msg":"notified peers this node is ready to join as voter","servers":["172.19.0.6:8300"],"time":"2024-07-18T18:55:09Z"}
storyden-weaviate-1  | {"action":"raft","last-leader-addr":"","last-leader-id":"","level":"warning","msg":"raft heartbeat timeout reached, starting election","time":"2024-07-18T18:55:09Z"}
storyden-weaviate-1  | {"action":"raft","level":"info","msg":"raft entering candidate state","node":{},"term":14,"time":"2024-07-18T18:55:09Z"}
storyden-weaviate-1  | {"action":"raft","level":"info","msg":"raft election won","tally":1,"term":14,"time":"2024-07-18T18:55:09Z"}
storyden-weaviate-1  | {"action":"raft","leader":{},"level":"info","msg":"raft entering leader state","time":"2024-07-18T18:55:09Z"}
storyden-weaviate-1  | {"cmd_class":"ContentOpenAI","cmd_type":2,"cmd_type_name":"TYPE_UPDATE_CLASS","error":"updating schema: TYPE_UPDATE_CLASS: bad request :parse class update: properties cannot be updated through updating the class. Use the add property feature (e.g. \"POST /v1/schema/{className}/properties\") to add additional properties","level":"error","log_index":7,"log_name":"LogCommand","log_type":0,"msg":"apply command","time":"2024-07-18T18:55:09Z"}
storyden-weaviate-1  | {"level":"info","msg":"reload local db: update schema ...","time":"2024-07-18T18:55:09Z"}
storyden-weaviate-1  | {"index":"ContentText2vecTransformers","level":"info","msg":"reload local index","time":"2024-07-18T18:55:09Z"}
storyden-weaviate-1  | {"index":"ContentOpenAI","level":"info","msg":"reload local index","time":"2024-07-18T18:55:09Z"}
storyden-weaviate-1  | {"address":"172.19.0.6:8300","level":"info","msg":"current Leader","time":"2024-07-18T18:55:09Z"}
storyden-weaviate-1  | panic: runtime error: invalid memory address or nil pointer dereference
storyden-weaviate-1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x176cb16]
storyden-weaviate-1  | 
storyden-weaviate-1  | goroutine 210 [running]:
storyden-weaviate-1  | github.com/weaviate/weaviate/modules/text2vec-transformers.(*TransformersModule).Arguments(0xc000674cd0?)
storyden-weaviate-1  |  /go/src/github.com/weaviate/weaviate/modules/text2vec-transformers/nearText.go:26 +0x16
storyden-weaviate-1  | github.com/weaviate/weaviate/usecases/modules.(*Provider).GetArguments(0xc002e84d70, 0xc000678160)
storyden-weaviate-1  |  /go/src/github.com/weaviate/weaviate/usecases/modules/modules.go:356 +0x204
storyden-weaviate-1  | github.com/weaviate/weaviate/adapters/handlers/graphql/local/get.buildGetClassField(0x412ba5?, 0xc000678160, {0x2170b20?, 0xc002e84d70}, 0xc000674f60?)
storyden-weaviate-1  |  /go/src/github.com/weaviate/weaviate/adapters/handlers/graphql/local/get/class_builder_fields.go:242 +0x769
storyden-weaviate-1  | github.com/weaviate/weaviate/adapters/handlers/graphql/local/get.(*classBuilder).classField(0xc002b99e00, 0xc000678160, 0xc002f68390?)
storyden-weaviate-1  |  /go/src/github.com/weaviate/weaviate/adapters/handlers/graphql/local/get/class_builder.go:102 +0xde
storyden-weaviate-1  | github.com/weaviate/weaviate/adapters/handlers/graphql/local/get.(*classBuilder).kinds(0xc003c0c0b0?, 0xc002b99dc0)
storyden-weaviate-1  |  /go/src/github.com/weaviate/weaviate/adapters/handlers/graphql/local/get/class_builder.go:83 +0x21c
storyden-weaviate-1  | github.com/weaviate/weaviate/adapters/handlers/graphql/local/get.(*classBuilder).objects(...)
storyden-weaviate-1  |  /go/src/github.com/weaviate/weaviate/adapters/handlers/graphql/local/get/class_builder.go:65
storyden-weaviate-1  | github.com/weaviate/weaviate/adapters/handlers/graphql/local/get.Build(0xc003c0c0b0, {0x2182d10?, 0xc003a8a880?}, {0x2170b20?, 0xc002e84d70?})
storyden-weaviate-1  |  /go/src/github.com/weaviate/weaviate/adapters/handlers/graphql/local/get/get.go:47 +0x5d
storyden-weaviate-1  | github.com/weaviate/weaviate/adapters/handlers/graphql/local.Build(_, {_, _}, {{0x0, 0x0}, 0x0, {0x19}, 0x2710, 0x186a0, {{0x0, ...}}, ...}, ...)
storyden-weaviate-1  |  /go/src/github.com/weaviate/weaviate/adapters/handlers/graphql/local/local.go:29 +0x4c
storyden-weaviate-1  | github.com/weaviate/weaviate/adapters/handlers/graphql.buildGraphqlSchema(_, {_, _}, {{0x0, 0x0}, 0x0, {0x19}, 0x2710, 0x186a0, {{0x0, ...}}, ...}, ...)
storyden-weaviate-1  |  /go/src/github.com/weaviate/weaviate/adapters/handlers/graphql/schema.go:87 +0x87
storyden-weaviate-1  | github.com/weaviate/weaviate/adapters/handlers/graphql.Build(_, {_, _}, {_, _}, {{0x0, 0x0}, 0x0, {0x19}, 0x2710, ...}, ...)
storyden-weaviate-1  |  /go/src/github.com/weaviate/weaviate/adapters/handlers/graphql/schema.go:57 +0x205
storyden-weaviate-1  | github.com/weaviate/weaviate/adapters/handlers/rest.rebuildGraphQL({_}, {_, _}, {{0x0, 0x0}, 0x0, {0x19}, 0x2710, 0x186a0, {{0x0, ...}}, ...}, ...)
storyden-weaviate-1  |  /go/src/github.com/weaviate/weaviate/adapters/handlers/rest/configure_server.go:70 +0xe5
storyden-weaviate-1  | github.com/weaviate/weaviate/adapters/handlers/rest.MakeAppState.makeUpdateSchemaCall.func6({0x0?})
storyden-weaviate-1  |  /go/src/github.com/weaviate/weaviate/adapters/handlers/rest/configure_server.go:52 +0xde
storyden-weaviate-1  | github.com/weaviate/weaviate/usecases/schema.(*executor).TriggerSchemaUpdateCallbacks(0xc0006221c0)
storyden-weaviate-1  |  /go/src/github.com/weaviate/weaviate/usecases/schema/executor.go:242 +0x14f
storyden-weaviate-1  | github.com/weaviate/weaviate/usecases/schema.(*executor).ReloadLocalDB(0xc0006221c0, {0x216b300, 0x4781300}, {0xc003b77820, 0x2, 0x0?})
storyden-weaviate-1  |  /go/src/github.com/weaviate/weaviate/usecases/schema/executor.go:66 +0x4c5
storyden-weaviate-1  | github.com/weaviate/weaviate/cluster/schema.(*SchemaManager).ReloadDBFromSchema(0xc00060d7d0)
storyden-weaviate-1  |  /go/src/github.com/weaviate/weaviate/cluster/schema/manager.go:124 +0x197
storyden-weaviate-1  | github.com/weaviate/weaviate/cluster.(*Store).reloadDBFromSchema(0xc003b0e000)
storyden-weaviate-1  |  /go/src/github.com/weaviate/weaviate/cluster/store.go:616 +0x25
storyden-weaviate-1  | github.com/weaviate/weaviate/cluster.(*Store).Apply.func1()
storyden-weaviate-1  |  /go/src/github.com/weaviate/weaviate/cluster/store_apply.go:107 +0x2d4
storyden-weaviate-1  | github.com/weaviate/weaviate/cluster.(*Store).Apply(0xc003b0e000, 0xc0037e58c0)
storyden-weaviate-1  |  /go/src/github.com/weaviate/weaviate/cluster/store_apply.go:211 +0xe28
storyden-weaviate-1  | github.com/hashicorp/raft.(*Raft).runFSM.func1(0xc0027fee10)
storyden-weaviate-1  |  /go/pkg/mod/github.com/hashicorp/raft@v1.5.0/fsm.go:101 +0x224
storyden-weaviate-1  | github.com/hashicorp/raft.(*Raft).runFSM.func2({0xc002980000, 0xb, 0x4?})
storyden-weaviate-1  |  /go/pkg/mod/github.com/hashicorp/raft@v1.5.0/fsm.go:124 +0x462
storyden-weaviate-1  | github.com/hashicorp/raft.(*Raft).runFSM(0xc00381b080)
storyden-weaviate-1  |  /go/pkg/mod/github.com/hashicorp/raft@v1.5.0/fsm.go:240 +0x3e8
storyden-weaviate-1  | github.com/hashicorp/raft.(*raftState).goFunc.func1()
storyden-weaviate-1  |  /go/pkg/mod/github.com/hashicorp/raft@v1.5.0/state.go:149 +0x53
storyden-weaviate-1  | created by github.com/hashicorp/raft.(*raftState).goFunc in goroutine 109
storyden-weaviate-1  |  /go/pkg/mod/github.com/hashicorp/raft@v1.5.0/state.go:147 +0x79
storyden-weaviate-1 exited with code 2
```

### Supporting information

My assumption, based on some of the errors is that I cannot add a new module to an existing index. Which makes sense somewhat.

I did fix it by deleting the data entirely and running it again, which is fine because our content re-indexes automatically. But on a larger installation with lots of content, this is not ideal.

If adding a module is just not possible for technical reasons, it makes sense - in this case I'll document this for our users to ensure they enable everything they know they will be using and warn about the need to delete+re-index if any Weaviate configs change.

### Server Version

1.25.7

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by dirkkul** [comment]
please update to 1.25.8 :)

**Comment by Southclaws** [comment]
Ah, thanks!
