### ISSUE TITLE
GSE tokenizer failed.

### ISSUE THREAD

**Issue by zhiwehu** [weaviate/weaviate#5805]
### How to reproduce this bug?

I use the command to run the weaviate on ubuntu 22.04:

```shell
./weaviate --host 0.0.0.0 --port 8888 --scheme http
```

and here is my ENV:
```
export AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
export PERSISTENCE_DATA_PATH=/home/admin/weaviate
export ENABLE_MODULES=''
export CLUSTER_HOSTNAME='node1'
export ENABLE_TOKENIZER_GSE=true
export DEFAULT_VECTORIZER_MODULE=none
export QUERY_DEFAULTS_LIMIT=25
```

When I run this Python code to insert data to a collection:
```python
# load数据文件
qa_pairs = [
    {"question": "特斯拉的纵梁尺寸是多少？", "answer": "1414"},
]

weaviate_client = weaviate.connect_to_local(
    host = "localhost",
    port = 8888
)

if weaviate_client.collections.exists(db_name):
    weaviate_client.collections.delete(db_name)

weaviate_client.collections.create(
    db_name,
    properties = [
        Property(
            name = "question",
            data_type = DataType.TEXT,
            tokenization = Tokenization.GSE
        ),
        Property(
            name = "answer",
            data_type = DataType.TEXT,
            tokenization = Tokenization.GSE
        ),
    ]
)

collection = weaviate_client.collections.get(db_name)
embeddings = embedding.embed_documents([f"{qa['question']} {qa['answer']}" for qa in qa_pairs])

for idx, qa in enumerate(qa_pairs):
    data_properties = {
        "question": qa["question"],
        "answer": str(qa["answer"])
    }
    obj_uuid = generate_uuid5(data_properties)
    collection.data.insert(
        properties = data_properties,
        vector = embeddings[idx],
        uuid = obj_uuid
    )

weaviate_client.close()
```
I got the error like this:

```
{"build_git_commit":"'\"$GITHASH\"'","build_go_version":"go1.21.13","build_image_tag":"localhost","build_wv_version":"1.26.4","error":"runtime error: invalid memory address or nil pointer dereference","level":"error","method":"POST","msg":"runtime error: invalid memory address or nil pointer dereference","path":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/v1/objects","RawPath":"","OmitHost":false,"ForceQuery":false,"RawQuery":"","Fragment":"","RawFragment":""},"time":"2024-09-14T22:06:17+08:00"}
{"action":"requests_total","api":"rest","build_git_commit":"'\"$GITHASH\"'","build_go_version":"go1.21.13","build_image_tag":"localhost","build_wv_version":"1.26.4","class_name":"","error":"runtime error: invalid memory address or nil pointer dereference","level":"error","msg":"unexpected error","query_type":"","time":"2024-09-14T22:06:17+08:00"}
goroutine 28503 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x13
github.com/weaviate/weaviate/adapters/handlers/rest.handlePanics({0x29141b0, 0xc003c93580}, {0x28f8e48, 0xc000123570}, 0xc002ecd700)
	/github/workspace/adapters/handlers/rest/panics_middleware.go:85 +0x2ff
panic({0x1e12a60?, 0x516e780?})
	/usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/go-ego/gse.(*Segmenter).Find(...)
	/go/pkg/mod/github.com/go-ego/gse@v0.80.2/dag.go:40
github.com/go-ego/gse.(*Segmenter).getDag(0x0, {0xc0028cef80, 0xc, 0x20})
	/go/pkg/mod/github.com/go-ego/gse@v0.80.2/dag.go:141 +0x207
github.com/go-ego/gse.(*Segmenter).cutAll(0xc0028cf0e8?, {0xc0053c4750, 0x24})
	/go/pkg/mod/github.com/go-ego/gse@v0.80.2/dag.go:317 +0xd5
github.com/go-ego/gse.(*Segmenter).CutAll(...)
	/go/pkg/mod/github.com/go-ego/gse@v0.80.2/gse.go:92
github.com/weaviate/weaviate/adapters/repos/db/helpers.tokenizeGSE({0xc0053c4750, 0x24})
	/github/workspace/adapters/repos/db/helpers/tokenizer.go:178 +0xee
github.com/weaviate/weaviate/adapters/repos/db/helpers.Tokenize({0xc002e10070?, 0xc0028cf1e8?}, {0xc0053c4750?, 0x2af?})
	/github/workspace/adapters/repos/db/helpers/tokenizer.go:86 +0x51
github.com/weaviate/weaviate/adapters/repos/db/inverted.(*Analyzer).TextArray(0x518bc80?, {0xc002e10070, 0x3}, {0xc0038a1530?, 0x1, 0x418a48?})
	/github/workspace/adapters/repos/db/inverted/analyzer.go:79 +0xfc
github.com/weaviate/weaviate/adapters/repos/db/inverted.(*Analyzer).Text(...)
	/github/workspace/adapters/repos/db/inverted/analyzer.go:71
github.com/weaviate/weaviate/adapters/repos/db/inverted.(*Analyzer).analyzePrimitiveProp(0xc0028cf9c8, 0xc0039a0b40, {0x1d0dc80, 0xc003b6fb90})
	/github/workspace/adapters/repos/db/inverted/objects.go:361 +0x8e5
github.com/weaviate/weaviate/adapters/repos/db/inverted.(*Analyzer).extendPropertiesWithPrimitive(0xc0028cf674?, 0xc0038a16c0, 0xc0028cf878?, 0xc0028cf6c0?, {0xc002e10068?, 0xd4b3a0?})
	/github/workspace/adapters/repos/db/inverted/objects.go:194 +0x67
github.com/weaviate/weaviate/adapters/repos/db/inverted.(*Analyzer).analyzeProps(0x1df1ec0?, 0xc0028cf7e0?, 0xc002e10090?)
	/github/workspace/adapters/repos/db/inverted/objects.go:88 +0x385
github.com/weaviate/weaviate/adapters/repos/db/inverted.(*Analyzer).Object(0xc00615a0f0?, 0xc002f32b78?, {0xc002918e20, 0x2, 0x1d0e080?}, {0xc0053c4780, 0x24})
	/github/workspace/adapters/repos/db/inverted/objects.go:38 +0x13f
github.com/weaviate/weaviate/adapters/repos/db.(*Shard).AnalyzeObject(0xc004e80000, 0xc006130000)
	/github/workspace/adapters/repos/db/shard_write_inverted.go:82 +0x41b
github.com/weaviate/weaviate/adapters/repos/db.(*Shard).updateInvertedIndexLSM(0xc004e80000, 0xc006130000, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, 0x0)
	/github/workspace/adapters/repos/db/shard_write_put.go:460 +0x6a
github.com/weaviate/weaviate/adapters/repos/db.(*Shard).putObjectLSM(0xc004e80000, 0xc006130000, {0xc002f32d50, 0x10, 0x10})
	/github/workspace/adapters/repos/db/shard_write_put.go:294 +0x405
github.com/weaviate/weaviate/adapters/repos/db.(*Shard).putOne(0xc004e80000, {0x3a84b87e912b6280?, 0xc0053c4780?}, {0xc002f32d50, 0x10, 0x10}, 0xc006130000)
	/github/workspace/adapters/repos/db/shard_write_put.go:47 +0x56
github.com/weaviate/weaviate/adapters/repos/db.(*Shard).PutObject(0xc004e80000, {0x28f9c48, 0xc000168d80}, 0xc006130000)
	/github/workspace/adapters/repos/db/shard_write_put.go:43 +0xbe
github.com/weaviate/weaviate/adapters/repos/db.(*LazyLoadShard).PutObject(0xc0056fc810, {0x28f9c48, 0xc000168d80}, 0xc0053c4780?)
	/github/workspace/adapters/repos/db/shard_lazyloader.go:204 +0x4f
github.com/weaviate/weaviate/adapters/repos/db.(*Index).putObject(0xc00017a280, {0x28f9c48, 0xc000168d80}, 0xc006130000, 0x0, 0x0?)
	/github/workspace/adapters/repos/db/index.go:696 +0x4db
github.com/weaviate/weaviate/adapters/repos/db.(*DB).PutObject(0x28f9c48?, {0x28f9c48, 0xc000168d80}, 0xc0039b0fc0, {0xc002caa000, 0x800, 0x800}, 0x0, 0x24?, 0xa)
	/github/workspace/adapters/repos/db/crud.go:42 +0x34b
github.com/weaviate/weaviate/usecases/objects.(*Manager).addObjectToConnectorAndSchema(0xc003f9ac80, {0x28f9c48, 0xc000168d80}, 0x0?, 0xc0039b0fc0, 0x725de0?)
	/github/workspace/usecases/objects/add.go:99 +0x574
github.com/weaviate/weaviate/usecases/objects.(*Manager).AddObject(0xc003f9ac80, {0x28f9c48, 0xc0056fdec0}, 0x0?, 0xc0039b0fc0, 0xc0028e8c98?)
	/github/workspace/usecases/objects/add.go:53 +0x345
github.com/weaviate/weaviate/adapters/handlers/rest.(*objectHandlers).addObject(0xc002f45b00, {0xc005648400?, 0xc0039b0fc0?, 0x0?}, 0x0?)
	/github/workspace/adapters/handlers/rest/handlers_objects.go:89 +0xe6
github.com/weaviate/weaviate/adapters/handlers/rest/operations/objects.ObjectsCreateHandlerFunc.Handle(0xc0028e8e00?, {0xc005648400?, 0xc0039b0fc0?, 0x0?}, 0xc003b785e8?)
	/github/workspace/adapters/handlers/rest/operations/objects/objects_create.go:32 +0x32
github.com/weaviate/weaviate/adapters/handlers/rest/operations/objects.(*ObjectsCreate).ServeHTTP(0xc0000108b8, {0x28f4a88, 0xc00015b420}, 0xc005648400)
	/github/workspace/adapters/handlers/rest/operations/objects/objects_create.go:81 +0x287
github.com/go-openapi/runtime/middleware.(*Context).RoutesHandler.NewOperationExecutor.func1({0x28f4a88, 0xc00015b420}, 0xc005648400)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.24.2/middleware/operation.go:28 +0x53
net/http.HandlerFunc.ServeHTTP(0xc0039b0d80?, {0x28f4a88?, 0xc00015b420?}, 0xc005648300?)
	/usr/local/go/src/net/http/server.go:2141 +0x29
github.com/weaviate/weaviate/adapters/handlers/rest.configureAPI.makeSetupMiddlewares.func7.1({0x28f4a88, 0xc00015b420}, 0xc005648400)
	/github/workspace/adapters/handlers/rest/middlewares.go:46 +0xdf
net/http.HandlerFunc.ServeHTTP(0x418a48?, {0x28f4a88?, 0xc00015b420?}, 0xc0028e8f08?)
	/usr/local/go/src/net/http/server.go:2141 +0x29
github.com/go-openapi/runtime/middleware.NewRouter.func1({0x28f4a88, 0xc00015b420}, 0xc002ecd700)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.24.2/middleware/router.go:78 +0x257
net/http.HandlerFunc.ServeHTTP(0x10?, {0x28f4a88?, 0xc00015b420?}, 0x7fd47307e2a8?)
	/usr/local/go/src/net/http/server.go:2141 +0x29
github.com/go-openapi/runtime/middleware.Redoc.func1({0x28f4a88, 0xc00015b420}, 0x1b7df45?)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.24.2/middleware/redoc.go:72 +0x22e
net/http.HandlerFunc.ServeHTTP(0x218900a?, {0x28f4a88?, 0xc00015b420?}, 0x410a05?)
	/usr/local/go/src/net/http/server.go:2141 +0x29
github.com/go-openapi/runtime/middleware.Spec.func1({0x28f4a88, 0xc00015b420}, 0xc0028e9401?)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.24.2/middleware/spec.go:46 +0x182
net/http.HandlerFunc.ServeHTTP(0xc003f9b5e0?, {0x28f4a88?, 0xc00015b420?}, 0xc002ecd700?)
	/usr/local/go/src/net/http/server.go:2141 +0x29
github.com/rs/cors.(*Cors).Handler-fm.(*Cors).Handler.func1({0x28f4a88, 0xc00015b420}, 0xc002ecd700)
	/go/pkg/mod/github.com/rs/cors@v1.5.0/cors.go:200 +0x17e
net/http.HandlerFunc.ServeHTTP(0x0?, {0x28f4a88?, 0xc00015b420?}, 0xc0039b0d80?)
	/usr/local/go/src/net/http/server.go:2141 +0x29
github.com/weaviate/weaviate/adapters/handlers/rest/swagger_middleware.AddMiddleware.func1({0x28f4a88, 0xc00015b420}, 0xc002ecd700)
	/github/workspace/adapters/handlers/rest/swagger_middleware/swagger_middleware.go:37 +0x219
net/http.HandlerFunc.ServeHTTP(0xc000139c00?, {0x28f4a88?, 0xc00015b420?}, 0x3?)
	/usr/local/go/src/net/http/server.go:2141 +0x29
github.com/weaviate/weaviate/adapters/handlers/rest.makeAddLogging.func1.1({0x28f4a88, 0xc00015b420}, 0xc002ecd700)
	/github/workspace/adapters/handlers/rest/middlewares.go:153 +0x273
net/http.HandlerFunc.ServeHTTP(0x1fd07e0?, {0x28f4a88?, 0xc00015b420?}, 0x1c?)
	/usr/local/go/src/net/http/server.go:2141 +0x29
github.com/weaviate/weaviate/adapters/handlers/rest.addPreflight.func1({0x28f4a88, 0xc00015b420}, 0xc002ecd700)
	/github/workspace/adapters/handlers/rest/middlewares.go:190 +0x35b
net/http.HandlerFunc.ServeHTTP(0xc0039b0d80?, {0x28f4a88?, 0xc00015b420?}, 0xc00551c838?)
	/usr/local/go/src/net/http/server.go:2141 +0x29
github.com/weaviate/weaviate/adapters/handlers/rest.addLiveAndReadyness.func1({0x28f4a88, 0xc00015b420}, 0xc002ecd700)
	/github/workspace/adapters/handlers/rest/middlewares.go:229 +0xb0
net/http.HandlerFunc.ServeHTTP(0xc0039b0d80?, {0x28f4a88?, 0xc00015b420?}, 0xb?)
	/usr/local/go/src/net/http/server.go:2141 +0x29
github.com/weaviate/weaviate/adapters/handlers/rest.addHandleRoot.func1({0x28f4a88, 0xc00015b420}, 0xc002ecd700)
	/github/workspace/adapters/handlers/rest/middlewares.go:61 +0x1d9
net/http.HandlerFunc.ServeHTTP(0xc0039b0d80?, {0x28f4a88?, 0xc00015b420?}, 0x0?)
	/usr/local/go/src/net/http/server.go:2141 +0x29
github.com/weaviate/weaviate/adapters/handlers/rest.makeAddModuleHandlers.func1.1({0x28f4a88, 0xc00015b420}, 0xc002ecd700)
	/github/workspace/adapters/handlers/rest/middlewares.go:103 +0x92
net/http.HandlerFunc.ServeHTTP(0xc00551c960?, {0x28f4a88?, 0xc00015b420?}, 0xc00551c918?)
	/usr/local/go/src/net/http/server.go:2141 +0x29
github.com/weaviate/weaviate/adapters/handlers/rest.addInjectHeadersIntoContext.func1({0x28f4a88, 0xc00015b420}, 0xc002ecd700)
	/github/workspace/adapters/handlers/rest/middlewares.go:208 +0x20a
net/http.HandlerFunc.ServeHTTP(0xc003258be0?, {0x28f4a88?, 0xc00015b420?}, 0x0?)
	/usr/local/go/src/net/http/server.go:2141 +0x29
github.com/weaviate/weaviate/adapters/handlers/rest.makeCatchPanics.func1.1({0x28f4a88?, 0xc00015b420?}, 0x0?)
	/github/workspace/adapters/handlers/rest/panics_middleware.go:31 +0x98
net/http.HandlerFunc.ServeHTTP(0x0?, {0x28f4a88?, 0xc00015b420?}, 0x0?)
	/usr/local/go/src/net/http/server.go:2141 +0x29
github.com/weaviate/weaviate/adapters/handlers/rest.addClusterHandlerMiddleware.func1({0x28f4a88, 0xc00015b420}, 0xc002ecd700)
	/github/workspace/adapters/handlers/rest/middlewares.go:81 +0x102
net/http.HandlerFunc.ServeHTTP(0x410d85?, {0x28f4a88?, 0xc00015b420?}, 0xc00015b401?)
	/usr/local/go/src/net/http/server.go:2141 +0x29
net/http.serverHandler.ServeHTTP({0x28ec520?}, {0x28f4a88?, 0xc00015b420?}, 0x6?)
	/usr/local/go/src/net/http/server.go:2943 +0x8e
net/http.(*conn).serve(0xc0039a1200, {0x28f9c48, 0xc003839b90})
	/usr/local/go/src/net/http/server.go:2014 +0x5f4
created by net/http.(*Server).Serve in goroutine 250
	/usr/local/go/src/net/http/server.go:3091 +0x5cb
```

BTW, if I use docker compose up -d to run the weaviate, there is no this issue. Please help me to find if I missed something or do something wrong?

Thanks.

### What is the expected behavior?

should insert success

### What is the actual behavior?

got wrong

### Server Version

1.26.4

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by donomii** [comment]
Are you running this on the same machine that you built it on?
Unfortunately, the gse parser has a data directory that doesn't get built
into the binary.  On my system it is at

***@***.***/data/


if that still doesn't work, you may have to run weaviate using "go run"
rather than the binary.

We are currently working on other parsers that do not have this problem.

**Comment by zhiwehu** [comment]
Thanks @donomii 

May I ask where should I put the "data" directory ? is it in the user home root ?

And how to run via "go run" ?

**Comment by donomii** [comment]
The data directory should be downloaded when you use "ro run" , so try
using our convenient development script e.g.



./tools/dev/run_dev_server.sh local-gpt4all


look inside the file to see more options, such as other AI options.  (Don't
forget to set the GSE environment variable too)
