### ISSUE TITLE
 runtime error: invalid memory address or nil pointer dereference  when bulk inserting

### ISSUE THREAD

**Issue by roblatham00** [weaviate/weaviate#6601]
### How to reproduce this bug?

I am trying to adapt quickstart (https://weaviate.io/developers/weaviate/quickstart#22-add-objects) to use `text2vec-openai`

= weaviate server =

    ${HOME}/src/weaviate/tools/dev/run_dev_server.sh local-openai 

= weaviate client =

``` python
import weaviate
import weaviate.classes as wvc
import os
import requests
import json
import urllib
from requests_file import FileAdapter

client = weaviate.connect_to_local()

openai_key = os.getenv("OPENAI_APIKEY")
headers = {
    "X-OpenAI-Api-Key": openai_key,
    }

try:
    client.collections.delete("Question")

    questions = client.collections.create(
        name = "Question",
        vector_index_config=wvc.config.Configure.VectorIndex.flat(
            quantizer=wvc.config.Configure.VectorIndex.Quantizer.bq(
                rescore_limit=200,
                cache=True
            ),
        ),
        vectorizer_config=wvc.config.Configure.Vectorizer.text2vec_openai(
            model=None,
            base_url="https://my-openai-proxy"  # obviously set this for your site
        ),
        properties=[
            wvc.config.Property(name="answer", data_type=wvc.config.DataType.TEXT),
            wvc.config.Property(name="question", data_type=wvc.config.DataType.TEXT),
            wvc.config.Property(name="category", data_type=wvc.config.DataType.TEXT),
        ]
    )
    resp = requests.get('https://raw.githubusercontent.com/weaviate-tutorials/quickstart/main/data/jeopardy_tiny.json')
    data = json.loads(resp.text)
    questions = client.collections.get("Question")
    with questions.batch.dynamic() as batch:
        for d in data:
            batch.add_object({
               "answer": d["Answer"],
               "question": d["Question"],
               "category": d["Category"],
            })
    print("failed_objects: " , str(questions.batch.failed_objects))
    print("failed_references: " , str(questions.batch.failed_references))

finally:
    client.close()
 ```
 
 when I run this import I can create the collection but batch import gives me this error (I've truncated the listed objects to just the first ErrorObject, but all ten are the same)
 
```
{'message': 'Failed to send 10 objects in a batch of 10. Please inspect client.batch.failed_objects or collection.batch.failed_objects for the failed objects.'}
failed_objects:  [ErrorObject(message='WeaviateBatchError(\'Query call with protocol GRPC batch failed with message <AioRpcError of RPC that terminated with:\\n\\tstatus = StatusCode.UNKNOWN\\n\\tdetails = "panic occurred: runtime error: invalid memory address or nil pointer dereference"\\n\\tdebug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"panic occurred: runtime error: invalid memory address or nil pointer dereference", grpc_status:2, created_time:"2024-12-11T19:52:48.901612803+00:00"}"\\n>.\')', object_=_BatchObject(collection='Question', vector=None, uuid='f305de1a-4d41-4d82-9e17-0b8f599a4e5f', properties={'answer': 'Liver', 'question': 'This organ removes excess glucose from the blood & stores it as glycogen', 'category': 'SCIENCE'}, tenant=None, references=None, index=0, retry_count=0), original_uuid=None), ...
```

The server log contains this backtrace:
```
INFO[0045] Created shard question_RGa7yJybfTy1 in 93.517033ms  build_git_commit=9069628b build_go_version=go1.23.2 build_image_tag=release-1.28.0 build_wv_version=1.28.0
ERRO[0045] Recovered from panic: runtime error: invalid memory address or nil pointer dereference  build_git_commit=9069628b build_go_version=go1.23.2 build_image_tag=release-1.28.0 build_wv_version=1.28.0
goroutine 239419 [running]:
runtime/debug.Stack()
        /home/robl/src/go/src/runtime/debug/stack.go:26 +0x5e
runtime/debug.PrintStack()
        /home/robl/src/go/src/runtime/debug/stack.go:18 +0x13
github.com/weaviate/weaviate/entities/errors.GoWrapperWithErrorCh.func1.1()
        /home/robl/src/weaviate/entities/errors/go_wrapper.go:48 +0x152
panic({0x207b280?, 0x5fea000?})
        /home/robl/src/go/src/runtime/panic.go:785 +0x132
github.com/weaviate/tiktoken-go.(*Tiktoken).Encode(0x0, {0xc004946100, 0x78}, {0x0?, 0x0?, 0xc003c5cd80?}, {0x0, 0x0, 0x0?})
        /home/robl/go/pkg/mod/github.com/weaviate/tiktoken-go@v0.0.2/tiktoken.go:81 +0x392
github.com/weaviate/weaviate/modules/text2vec-openai/clients.GetTokensCount({0x0?, 0x35c0028?}, {0xc004946100?, 0x0?}, 0x35c4ea0?)
        /home/robl/src/weaviate/modules/text2vec-openai/clients/openai_tokens.go:27 +0xa8
github.com/weaviate/weaviate/modules/text2vec-openai.(*OpenAIModule).initVectorizer.ReturnBatchTokenizer.func1({0x35c0028, 0xc003d99a40}, {0xc005fcfd00, 0xa, 0x417885?}, {0xc0067960c0, 0xa, 0x2b?}, {0x35c5160, 0xc003f19e40}, ...)
        /home/robl/src/weaviate/usecases/modulecomponents/batch/tokenization.go:54 +0x28c
github.com/weaviate/weaviate/usecases/modulecomponents/text2vecbase.(*BatchVectorizer[...]).ObjectBatch(0x35d2a40, {0x35c0028, 0xc003d99a40}, {0xc005fcfd00, 0xa?, 0xc005670c98}, {0xc0067960c0, 0xa, 0xa}, {0x35c5160?, ...})
        /home/robl/src/weaviate/usecases/modulecomponents/text2vecbase/batch_vectorizer.go:63 +0x9b
github.com/weaviate/weaviate/modules/text2vec-openai.(*OpenAIModule).VectorizeBatch(0x0?, {0x35c0028?, 0xc003d99a40?}, {0xc005fcfd00?, 0xc003d99a40?, 0x35c5160?}, {0xc0067960c0?, 0x7f9a6306a0a8?, 0xc004965810?}, {0x35c5160, ...})
        /home/robl/src/weaviate/modules/text2vec-openai/module.go:141 +0x4e
github.com/weaviate/weaviate/usecases/modules.(*Provider).batchUpdateVector(0xc00463c6c0, {0x35c0028, 0xc003d99a40}, {0xc005fcfd00, 0xa, 0x10}, 0xc007232210, 0xc003ff8ac0, {0x0, 0x0}, ...)
        /home/robl/src/weaviate/usecases/modules/vectorizer.go:210 +0x431
github.com/weaviate/weaviate/usecases/modules.(*Provider).BatchUpdateVector(0xc00463c6c0, {0x35c0028, 0xc003d99a40}, 0xc007232210, {0xc005fcfd00, 0xa, 0x10}, 0xc003ff8ac0, {0x35decb0, 0xc004398e80})
        /home/robl/src/weaviate/usecases/modules/vectorizer.go:110 +0x2b6
github.com/weaviate/weaviate/usecases/objects.(*BatchManager).validateAndGetVector(0xc0043d3050, {0x35c0028, 0xc003d99a40}, 0x0, {0xc0062ff540, 0xa, 0x7f9a63125c28?}, 0x0)
        /home/robl/src/weaviate/usecases/objects/batch_add.go:196 +0xbe7
github.com/weaviate/weaviate/usecases/objects.(*BatchManager).addObjects(0xc0043d3050, {0x35c0028?, 0xc003d98000?}, 0x0, {0xc0062ff540, 0xa, 0xa}, {0xc00532bea8, 0x1, 0x1}, ...)
        /home/robl/src/weaviate/usecases/objects/batch_add.go:86 +0x32d
github.com/weaviate/weaviate/usecases/objects.(*BatchManager).AddObjects(0xc0043d3050, {0x35c0028, 0xc003d98000}, 0x0, {0xc0062ff540, 0xa, 0xa}, {0xc00532bea8, 0x1, 0x1}, ...)
        /home/robl/src/weaviate/usecases/objects/batch_add.go:54 +0x439
github.com/weaviate/weaviate/adapters/handlers/grpc/v1.(*Service).batchObjects(0xc00311b900, {0x35c0028, 0xc003d98000}, 0xc0062feaa0)
        /home/robl/src/weaviate/adapters/handlers/grpc/v1/service.go:201 +0x4f8
github.com/weaviate/weaviate/adapters/handlers/grpc/v1.(*Service).BatchObjects.func1()
        /home/robl/src/weaviate/adapters/handlers/grpc/v1/service.go:141 +0x35
github.com/weaviate/weaviate/entities/errors.GoWrapperWithErrorCh.func1()
        /home/robl/src/weaviate/entities/errors/go_wrapper.go:53 +0x65
created by github.com/weaviate/weaviate/entities/errors.GoWrapperWithErrorCh in goroutine 239418
        /home/robl/src/weaviate/entities/errors/go_wrapper.go:42 +0xa5
DEBU[0045] grpc BatchObjects request (0.001884MB) took 389.752399ms  action=grpc_batch_objects build_git_commit=9069628b build_go_version=go1.23.2 build_image_tag=release-1.28.0 build_wv_version=1.28.0 duration=389.752399ms method=/weaviate.v1.Weaviate/BatchObjects request_size_bytes=1976```


### What is the expected behavior?

batch import succeeds

### What is the actual behavior?

invalid memory address deep inside `text2vec-openai` module

### Supporting information

I'm running weaviate locally
Server:
version: v1.28.0
go version go1.23.2 linux/amd64
Client:
python-3.11.9
weaviate-client        4.9.6

### Server Version

1.28.0

### Weaviate Setup

Single Node

### Nodes count

1

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by roblatham00** [comment]
Further investigation:  if I provide my own vectors (just made up some data), this memory error goes away.  

 I would like `text2vec-openai` to behave like other integrations and go get the embedding for me.  -- or maybe it tried to and failed but the error became a null thing?

**Comment by dudanogueira** [comment]
hi @roblatham00 !!

I was not able to reproduce this. I am using OpenAI, and not providing a base_url:

```python
import requests, json
questions = client.collections.create(
    name = "Question",
    vector_index_config=wvc.config.Configure.VectorIndex.flat(
        quantizer=wvc.config.Configure.VectorIndex.Quantizer.bq(
            rescore_limit=200,
            cache=True
        ),
    ),
    vectorizer_config=wvc.config.Configure.Vectorizer.text2vec_openai(
        model=None
    ),
    properties=[
        wvc.config.Property(name="answer", data_type=wvc.config.DataType.TEXT),
        wvc.config.Property(name="question", data_type=wvc.config.DataType.TEXT),
        wvc.config.Property(name="category", data_type=wvc.config.DataType.TEXT),
    ]
)
resp = requests.get('https://raw.githubusercontent.com/weaviate-tutorials/quickstart/main/data/jeopardy_tiny.json')
data = json.loads(resp.text)
questions = client.collections.get("Question")
with questions.batch.dynamic() as batch:
    for d in data:
        batch.add_object({
            "answer": d["Answer"],
            "question": d["Question"],
            "category": d["Category"],
        })
print("failed_objects: " , str(questions.batch.failed_objects))
print("failed_references: " , str(questions.batch.failed_references))
```

can you generate a vector at that url you providing as "https://my-openai-proxy"?

**Comment by dasurchek** [comment]
@dudanogueira I am seeing this error in an cluster which has outbound rules in place.  From looking at code suspect that weaviate is unable to download tiktoken dictionary.  Batch seems to use tiktoken, where single writes do not.

When was tiktoken introduced?

**Comment by dandv** [comment]
Caused by #12008.
